### ISSUE TITLE
Huobi default account is point account. Create order returns error.

### ISSUE THREAD

**Issue by andrelcgt** [ccxt/ccxt#10798]
I receive the error below, because since CCXT gets point account as the default it is trying to trade on an account that cannot make trades.
ccxt.base.errors.ExchangeError: huobi {"status":"error","err-code":"order-source-invalid","err-msg":"invalid order source `spot-api`","data":null}

https://github.com/ccxt/ccxt/blob/ea298413d5a7c1ac5d2fad044ca787c1c50830a7/python/ccxt/huobi.py#L1718

**Comment by kroitor** [comment]
@andrelcgt what is your version of CCXT? This was fixed a day ago.

**Comment by kroitor** [comment]
Please, upgrade your version of CCXT 1.63.9+ and paste your output with this code:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.huobi({
    "apiKey": "YOUR_API_KEY",
    "secret": "YOUR_SECRET",
    "apiKey": "b6c06a21-c5aa880d-mn8ikls4qg-3d815",
    "secret": "39591aa5-3759c9b2-dcfd4482-fb8d4",
})
markets = exchange.load_markets()
accounts = exchange.load_accounts()
pprint(accounts)
default_account_id = exchange.fetch_account_id_by_type('spot')
print('Default account id is', default_account_id)
```

**Comment by kroitor** [comment]
Feel free to reopen this issue if the above does not help.

**Comment by andrelcgt** [comment]
@kroitor the return of your code is below. However the error persist.
CCXT Version: 1.63.10
[{'id': '36403705', 'state': 'working', 'subtype': '', 'type': 'point'},
 {'id': '36520888', 'state': 'working', 'subtype': '', 'type': 'spot'}]
Default account id is 36520888

In create_order there is line 2147 which is:
accountId = self.fetch_account_id_by_type(type)
However the type variable contains the type of order ('market', 'limit'), and not the type of account ('point', or 'spot').
So when running create order the account used is still point and not spot.

**Comment by kroitor** [comment]
@andrelcgt yes, you're right, that was a bug in createOrder, i've pushed a fix to it just now, and it will arrive in 1.63.13+ in ~ 20 minutes. Thanks for pointing it out! Please let me know if that solves the issue for you or not. Tested on my side, it should work fine.
