### ISSUE TITLE
ccxt\ExchangeError safe_value2 method not found

### ISSUE THREAD

**Issue by legitalk** [ccxt/ccxt#12985]
- OS: Linux
- Programming Language version: PHP 8
- CCXT version: 1.80.56

Calling create_limit_sell_order() is failing on:
```
ccxt\ExchangeError
safe_value2 method not found
```
Looks like after update to newest version there is a typo in method, and it should be `safe_value_2()`, which is found in coinbasepro.php and gateio.php, but `safe_value2()` is not there.

```
ccxt\ExchangeError
safe_value2 method not found
```

**Comment by kroitor** [comment]
@legitalk thanks for reporting it! We've pushed a fix that will arrive in ~20 minutes in CCXT 1.80.57. Let us know if you have this issue after upgrading. Thx again!

**Comment by legitalk** [comment]
@kroitor the issue has been fixed, but there is another issue now:

```
Error
Call to undefined function ccxt\upper()
```

**Comment by kroitor** [comment]
@legitalk pardon for the inconvenience, there was one more typo/leftover, i've pushed another fix, should be ok now in 1.80.59 (the auto build will take ~20 minutes).

**Comment by legitalk** [comment]
@kroitor thank you, `strtoupper()` fixed the issue, but there is still another one in `create_limit_buy_order()`:

ErrorException
Undefined variable $type_lower

**Comment by kroitor** [comment]
@legitalk  thx for your feedback! Please, let me know if 1.80.60 does not solve it for you.

**Comment by legitalk** [comment]
@kroitor yes, that is fixed now, but again another issue in `create_limit_sell_order()`:

```
ccxt\ExchangeError
is_post_only method not found
```

**Comment by kroitor** [comment]
@legitalk which exchange is it? Please, paste your complete output:

```PHP

echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";

// instantiate the exchange by id
$exchange_id = '\\ccxt\\gateio';
$exchange = new $exchange_id(array(
    'api_key' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
));
$exchange->create_limit_sell_order($symbol, $amount, $price);
````

**Comment by legitalk** [comment]
@kroitor yes, that is fixed now, but again another issue in `create_limit_sell_order()` in Gateio exchange:

CCXT v1.80.60

```
create_limit_sell_order('10SET_USDT', 1000, 2.75);

ccxt\ExchangeError
is_post_only method not found
```

**Comment by kroitor** [comment]
@legitalk how do you update your version of CCXT ?

**Comment by legitalk** [comment]
@kroitor Sentry caught that error and I think, it was the previous version of CCXT (1.80.59), so before you fixed it. Looks like its fixed now in 1.80.60. If I will see the error again, I will let you know. Thank you very much.

**Comment by kroitor** [comment]
@legitalk thx for reporting it, please, don't hesitate if anything.
