### ISSUE TITLE
KuCoin not API fetching all orders and commissions/fees missing

### ISSUE THREAD

**Issue by pavitrakumar78** [ccxt/ccxt#13008]
Hi,

I'm not able to get all orders using the KuCoin API and also, commissions and fees for all orders are null:

- OS: Ubuntu 20.04
- Programming Language version: Python 3.8
- CCXT version: 1.72.89 

```
                all_future_trades = []
                exchange = ccxt.kucoinfutures({
                    'adjustForTimeDifference': True,
                    'enableRateLimit': True,
                    'apiKey': ...,
                    'secret': ...,
                    'password': ...,
                })
                now = exchange.milliseconds()
                day = 24 * 3600 * 1000
                week = 1 * day
                since = now - 180 * day
                limit = 5
                all_orders = []
                orders = []
                while since < now:
                    end = min(since + week, now)
                    params = {'endAt': end}
                    orders = exchange.fetch_closed_orders(since=since, limit=limit, params=params)
                    all_orders.extend(orders)
                    if len(orders) == limit:
                        since = orders[-1]['timestamp']
                    else:
                        since += week
                    time.sleep(0.25)
                    all_future_trades.extend(all_orders)
```

Note: I tried reducing the `week` from 7 days to 1 and `limit` from 10 to 5 and it shows slightly more orders, but still, it is missing a lot of orders compared to the kucoin console. 

Is there anything that I'm missing here or does the API not support KuCoin commissions? 

Thank you!

**Comment by dasbts** [comment]
First off, thank you for this example. It helped me at least start fetching something. I have been asking about that for a long time on Discord, specifically for Kucoin, since the data pagination examples, for some reason, don't work for either fetchMyTrade, fetchOrders, or fetchClosedOrders in that exchange (pretty sure it's because of their new API endpoint).

It seems like I get all my orders fetched when I change the limit to 500 and change the "since = now - 180 * day" to "since = now - 365 * day" as that's enough to catch all my trades, however, I'm using async if that makes any difference. 

I would probably change it, so instead of using the code in the above paragraph, start it from a given date, for example: 
# Sets the date to fetch from
chosen_date = "2021-01-01"
since = exchange.parse8601(chosen_date+'T00:00:00Z') 

Then I changed this according to the example for data pagination: 
`        if len(orders) == limit:
            #since = orders[-1]['timestamp']
            since = orders[len(orders) - 1]['timestamp'] + 1`

Oh and also, for some reason (probably the way of pagination) this adds about 56 000 more entries than I have, but these are just duplicates which I solved (and checked the length of) by adding the following: 
`deduplicated_list = list()
for item in trades_history_kucoin:
    if item not in deduplicated_list:
        deduplicated_list.append(item)
trades_history_kucoin = deduplicated_list
len(trades_history_kucoin)`

Also, I tried it on the spot market history. Hopefully, it's helpful for the futures market too. Cheers!

**Comment by pavitrakumar78** [comment]
@dasbts Thanks for the suggestions! The code above is not mine - I found it in this repo somewhere in one of the issues.

I'm still not able to see all of the transactions with your fix and the fees are still None for everything. 

How are you handling fees?

Another issue I have been having is the handling of size/quantity. Here is an example:

```
    {
        "id": "xyz",
        "clientOrderId": null,
        "symbol": "SOL/USDT:USDT",
        "type": "limit",
        "timeInForce": "GTC",
        "postOnly": false,
        "side": "sell",
        "amount": 250.0,
        "price": 118.315,
        "stopPrice": null,
        "cost": 2963.6521,
        "filled": 250.0,
        "remaining": 0.0,
        "timestamp": 1649271166000,
        "datetime": "2022-04-06T18:52:46.000Z",
        "fee": {
            "currency": null,
            "cost": null
        },
        "status": "closed",
        "info": {
            "id": "xyz",
            "symbol": "SOLUSDTM",
            "type": "limit",
            "side": "sell",
            "price": "118.315",
            "size": 250,
            "value": "2957.875",
            "dealValue": "2963.6521",
            "dealSize": 250,
            "stp": "",
            "stop": "",
            "stopPriceType": "",
            "stopTriggered": false,
            "stopPrice": null,
            "timeInForce": "GTC",
            "postOnly": false,
            "hidden": false,
            "iceberg": false,
            "leverage": "1",
            "forceHold": false,
            "closeOrder": false,
            "visibleSize": null,
            "clientOid": null,
            "remark": null,
            "tags": null,
            "isActive": false,
            "cancelExist": false,
            "createdAt": 1649271166000,
            "updatedAt": 1649271166755,
            "endAt": 1649271166755,
            "orderTime": 1649271166276998119,
            "settleCurrency": "USDT",
            "status": "done",
            "filledSize": 250,
            "filledValue": "2963.6521",
            "reduceOnly": true
        },
        "lastTradeTimestamp": null,
        "average": 118.546084,
        "trades": [],
        "fees": [
            {
                "currency": null,
                "cost": null
            }
        ]
    },
```

The quantity is supposed to be 25 (2957.875/118.315) - why is it reported as 250? Am I missing something here?

**Comment by dasbts** [comment]
Hmm, either it functions differently for the futures market, or maybe because you have an older CCXT library? Because I checked and I'm getting fees correctly, the right amount of trades and the right quantity traded. 
Try doing a "pip install ccxt --upgrade", I did so earlier today to something around 1.8, otherwise, if it's just for the futures market, you could always both manually adjust all the quantity values if they are wrongly corrected with a multiplier of 10, and you can always look at what fee % there is and apply that manually, that's what I had to do for Binance to save on currency conversion API calls.

**Comment by pavitrakumar78** [comment]
Tried upgrading to the latest version - still the same no commission/fees issue. 
Also, the constant of multiplying or diving by 10 does not apply to all the coins - that's why this is very confusing.

**Comment by samgermain** [comment]
> Note: I tried reducing the week from 7 days to 1 and limit from 10 to 5 and it shows slightly more orders, but still, it is missing a lot of orders compared to the kucoin console.

The kucoinfutures api is completely separate from the kucoin api, something being in the kucoin api has no impact on whether that thing will be in the kucoinfutures api

The kucoinfutures api has a narrow timerange, if I set the difference between `since` and `params.endAt` to just 9 days, I get a `time range invalid` error 

```
kucoinfutures.fetchClosedOrders(None,1633046400000,None,{'endAt': 1633737600000})
Traceback (most recent call last):
  File "/Users/sam/Documents/dev/CCXT/ccxt/examples/py/cli.py", line 193, in <module>
    result = method(*args)
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/kucoin.py", line 1336, in fetch_closed_orders
    return self.fetch_orders_by_status('done', symbol, since, limit, params)
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/kucoinfutures.py", line 1094, in fetch_orders_by_status
    response = getattr(self, method)(self.extend(request, params))
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/base/exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/base/exchange.py", line 547, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/base/exchange.py", line 543, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/base/exchange.py", line 698, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/kucoin.py", line 2440, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/base/exchange.py", line 561, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: kucoinfutures error.queryOrder.timeRangeInvalid
```

1633046400000 = Thu Sep 30 18:00:00 CST 2021
1633737600000 = Fri Oct  8 18:00:00 CST 2021

-----------------------

Is there anything that I'm missing here or does the API not support KuCoin commissions?

commissions aren't returned from this api endpoint, you can check the `info` param from the response to get the unmodified response from the exchange, and there's nothing about fees or commissions in there

```
  'info': {'cancelExist': False,
           'clientOid': None,
           'closeOrder': False,
           'createdAt': 1633396639000,
           'dealSize': 1,
           'dealValue': '34.053',
           'endAt': 1633396640660,
           'filledSize': 1,
           'filledValue': '34.053',
           'forceHold': False,
           'hidden': False,
           'iceberg': False,
           'id': '...',
           'isActive': False,
           'leverage': '5',
           'orderTime': 1633396639029370766,
           'postOnly': False,
           'price': '3406.65',
           'reduceOnly': False,
           'remark': None,
           'settleCurrency': 'USDT',
           'side': 'buy',
           'size': 1,
           'status': 'done',
           'stop': '',
           'stopPrice': None,
           'stopPriceType': '',
           'stopTriggered': False,
           'stp': '',
           'symbol': 'ETHUSDTM',
           'tags': None,
           'timeInForce': 'GTC',
           'type': 'limit',
           'updatedAt': 1633396640660,
           'value': '34.0665',
           'visibleSize': None},
 ```
 
 ------------------------
 
 You can use the `calculateFee (symbol, type, side, amount, price, takerOrMaker = 'taker', params = {}) {
` method, inherited from `base/exchange.py` to calculate an approximate fee

**Comment by pavitrakumar78** [comment]
Thanks for the suggestions!
