### ISSUE TITLE
Bybit C# WatchPositions hangs and do not receive updates

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#21565]
### CCXT Version

4.2.58

### Description

I am trying to receive positions (from only one symbol) from the WS in C# like this:

```
var symbols = new List<string>() { symbol };
var positions = await exchange.watchPositions(symbols:symbols);
```

In python, I do 
`await exchange.watch_positions(symbols=[symbol], limit=10)`
and it works. Although I need to call it twice cause the first time it just return an empty array []. 
But with C#, it never receives the message it seems.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @nikky78 thanks for letting us know, we will take a look

**Comment by nikky78** [comment]
Hi Carlos. So you pulled a new version that fixed both the watchPosition and how to retrieve the data, right? Could you explain a bit how I could use it, please?

**Comment by carlosmiei** [comment]
@nikky78 I merged the PR that fixes the reported issue, but we didn't release it (will do in a few hours). After the new release, you can update your ccxt version and use it as you would in the python version.

**Comment by nikky78** [comment]
I see in #21585 that the build has failed though

**Comment by carlosmiei** [comment]
@nikky78 That was an unrelated issue with the live tests

**Comment by nikky78** [comment]
my bad ^^'

**Comment by nikky78** [comment]
I tried with version 4.2.64 and still dont receive positions on bybit

**Comment by carlosmiei** [comment]
@nikky78 Oh sorry, let me check again

**Comment by carlosmiei** [comment]
@nikky78 Can you enable the verbose mode and post it?

I just tested and seems to work

```
> ccxt@4.2.64 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" bybit WatchPositions --sandbox

/Users/cjg/Git/ccxt10/ccxt/cs/cli/Program.cs(146,13): warning CS0162: Unreachable code detected [/Users/cjg/Git/ccxt10/ccxt/cs/cli/cli.csproj]
[]
[
  {
    "symbol": "LTC/USDT:USDT",
    "id": null,
    "info": {
      "symbol": "LTCUSDT",
      "leverage": "6",
      "autoAddMargin": 0,
      "avgPrice": "68.85",
      "liqPrice": "58.07",
      "riskLimitValue": "200000",
      "takeProfit": "",
      "positionValue": "13.77",
      "isReduceOnly": false,
      "tpslMode": "Full",
      "riskId": 71,
      "trailingStop": "0",
      "unrealisedPnl": "3.572",
      "markPrice": "86.71",
      "adlRankIndicator": 2,
      "cumRealisedPnl": "-46.08492245",
      "positionMM": "0.14401135",
      "createdTime": "1677168085779",
      "positionIdx": 0,
      "positionIM": "2.30131139",
      "seq": 15885008639,
      "updatedTime": "1709827200408",
      "side": "Buy",
      "bustPrice": "",
      "positionBalance": "2.30131139",
      "leverageSysUpdatedTime": "",
      "curRealisedPnl": "-0.05839597",
      "size": "0.2",
      "positionStatus": "Normal",
      "mmrSysUpdatedTime": "1698293363950",
      "stopLoss": "",
      "tradeMode": 0,
      "sessionAvgPrice": "",
      "nextPageCursor": "ETHUSDT%2C1709827200238%2C0"
    },
    "timestamp": 1709827200408.0,
    "datetime": "2024-03-07T16:00:00.408Z",
    "contracts": 0.2,
    "contractsSize": null,
    "side": "long",
    "notional": 13.77,
    "leverage": 6.0,
    "unrealizedPnl": 3.572,
    "realizedPnl": null,
    "collateral": 2.30131139,
    "entryPrice": 68.85,
    "markPrice": 86.71,
    "liquidationPrice": 58.07,
    "stopLossPrice": null,
    "takeProfitPrice": null,
    "marginMode": null,
    "hedged": null,
    "maintenenceMargin": null,
    "maintenanceMarginPercentage": null,
    "initialMargin": 2.295,
    "initialMarginPercentage": 0.16666666666666666,
    "marginRatio": null,
    "lastUpdateTimestamp": null,
    "lastPrice": null,
    "percentage": null
  },
  {
    "symbol": "XMR/USDT:USDT",
    "id": null,
    "info": {
      "symbol": "XMRUSDT",
      "leverage": "10",
      "autoAddMargin": 0,
      "avgPrice": "170.925",
      "liqPrice": "182.88",
      "riskLimitValue": "100000",
      "takeProfit": "",
      "positionValue": "167.5065",
      "isReduceOnly": false,
      "tpslMode": "Full",
      "riskId": 1,
      "trailingStop": "0",
      "unrealisedPnl": "25.3183",
      "markPrice": "145.09",
      "adlRankIndicator": 2,
      "cumRealisedPnl": "9.64182005",
      "positionMM": "5.12653644",
      "createdTime": "1701192869040",
      "positionIdx": 0,
      "positionIM": "16.85199144",
      "seq": 28075523508,
      "updatedTime": "1709827200408",
      "side": "Sell",
      "bustPrice": "",
      "positionBalance": "16.85199144",
      "leverageSysUpdatedTime": "",
      "curRealisedPnl": "8.85080665",
      "size": "0.98",
      "positionStatus": "Normal",
      "mmrSysUpdatedTime": "",
      "stopLoss": "",
      "tradeMode": 0,
      "sessionAvgPrice": ""
    },
    "timestamp": 1709827200408.0,
    "datetime": "2024-03-07T16:00:00.408Z",
    "contracts": 0.98,
    "contractsSize": null,
    "side": "short",
    "notional": 167.5065,
    "leverage": 10.0,
    "unrealizedPnl": 25.3183,
    "realizedPnl": null,
    "collateral": 16.85199144,
    "entryPrice": 170.925,
    "markPrice": 145.09,
    "liquidationPrice": 182.88,
    "stopLossPrice": null,
    "takeProfitPrice": null,
    "marginMode": null,
    "hedged": null,
    "maintenenceMargin": null,
    "maintenanceMarginPercentage": null,
    "initialMargin": 16.75065,
    "initialMarginPercentage": 0.1,
    "marginRatio": null,
    "lastUpdateTimestamp": null,
    "lastPrice": null,
    "percentage": null
  },
  {
    "symbol": "ETH/USDT:USDT",
    "id": null,
    "info": {
      "symbol": "ETHUSDT",
      "leverage": "10",
      "autoAddMargin": 0,
      "avgPrice": "3782.11",
      "liqPrice": "4141.41",
      "riskLimitValue": "900000",
      "takeProfit": "",
      "positionValue": "37.8211",
      "isReduceOnly": false,
      "tpslMode": "Full",
      "riskId": 11,
      "trailingStop": "0",
      "unrealisedPnl": "-0.7531",
      "markPrice": "3857.42",
      "adlRankIndicator": 2,
      "cumRealisedPnl": "-40.5401062",
      "positionMM": "0.21198727",
      "createdTime": "1694787586926",
      "positionIdx": 0,
      "positionIM": "3.80499177",
      "seq": 11172225697,
      "updatedTime": "1709827200238",
      "side": "Sell",
      "bustPrice": "",
      "positionBalance": "3.80499177",
      "leverageSysUpdatedTime": "",
      "curRealisedPnl": "0.00969504",
      "size": "0.01",
      "positionStatus": "Normal",
      "mmrSysUpdatedTime": "",
      "stopLoss": "",
      "tradeMode": 0,
      "sessionAvgPrice": ""
    },
    "timestamp": 1709827200238.0,
    "datetime": "2024-03-07T16:00:00.238Z",
    "contracts": 0.01,
    "contractsSize": null,
    "side": "short",
    "notional": 37.8211,
    "leverage": 10.0,
    "unrealizedPnl": -0.7531,
    "realizedPnl": null,
    "collateral": 3.80499177,
    "entryPrice": 3782.11,
    "markPrice": 3857.42,
    "liquidationPrice": 4141.41,
    "stopLossPrice": null,
    "takeProfitPrice": null,
    "marginMode": null,
    "hedged": null,
    "maintenenceMargin": null,
    "maintenanceMarginPercentage": null,
    "initialMargin": 3.78211,
    "initialMarginPercentage": 0.1,
    "marginRatio": null,
    "lastUpdateTimestamp": null,
    "lastPrice": null,
    "percentage": null
  },
  {
    "symbol": "XRP/USD:XRP",
    "id": null,
    "info": {
      "positionIdx": 0,
      "riskId": 31,
      "riskLimitValue": "750000",
      "symbol": "XRPUSD",
      "side": "Sell",
      "size": "1",
      "avgPrice": "0.5074",
      "positionValue": "1.97083169",
      "tradeMode": 0,
      "positionStatus": "Normal",
      "autoAddMargin": 1,
      "adlRankIndicator": 2,
      "leverage": "10",
      "positionBalance": "0.57042496",
      "markPrice": "0.6256",
      "liqPrice": "",
      "bustPrice": "199.9998",
      "positionMM": "0.00005",
      "positionIM": "0.03941663",
      "tpslMode": "Full",
      "takeProfit": "0.0000",
      "stopLoss": "0.0000",
      "trailingStop": "0.0000",
      "unrealisedPnl": "-0.37236622",
      "cumRealisedPnl": "0.03714892",
      "curRealisedPnl": "0.03853953",
      "seq": 2920329003,
      "isReduceOnly": false,
      "mmrSysUpdateTime": "",
      "leverageSysUpdatedTime": "",
      "sessionAvgPrice": "",
      "createdTime": "1707169185250",
      "updatedTime": "1709827200015"
    },
    "timestamp": 1709827200015.0,
    "datetime": "2024-03-07T16:00:00.015Z",
    "contracts": 1.0,
    "contractsSize": null,
    "side": "short",
    "notional": 1.97083169,
    "leverage": 10.0,
    "unrealizedPnl": -0.37236622,
    "realizedPnl": null,
    "collateral": 0.57042496,
    "entryPrice": 0.5074,
    "markPrice": 0.6256,
    "liquidationPrice": null,
    "stopLossPrice": 0.0,
    "takeProfitPrice": 0.0,
    "marginMode": null,
    "hedged": null,
    "maintenenceMargin": null,
    "maintenanceMarginPercentage": 2.5370000012532E-05,
    "initialMargin": 0.03941663,
    "initialMarginPercentage": 0.01999999807188,
    "marginRatio": 0.0,
    "lastUpdateTimestamp": null,
    "lastPrice": null,
    "percentage": null
  }
]
 








[
  {
    "symbol": "LTC/USDT:USDT",
    "id": null,
    "info": {
      "positionIdx": 0,
      "tradeMode": 0,
      "riskId": 71,
      "riskLimitValue": "200000",
      "symbol": "LTCUSDT",
      "side": "Buy",
      "size": "0.1",
      "entryPrice": "68.85",
      "sessionAvgPrice": "",
      "leverage": "6",
      "positionValue": "6.885",
      "positionBalance": "1.1506557",
      "markPrice": "86.77",
      "positionIM": "1.1506557",
      "positionMM": "0.07200568",
      "takeProfit": "0",
      "stopLoss": "0",
      "trailingStop": "0",
      "unrealisedPnl": "1.792",
      "cumRealisedPnl": "-44.29669535",
      "curRealisedPnl": "1.72983113",
      "createdTime": "1677168085779",
      "updatedTime": "1709836550251",
      "tpslMode": "Full",
      "liqPrice": "58.07",
      "bustPrice": "",
      "category": "linear",
      "positionStatus": "Normal",
      "adlRankIndicator": 2,
      "autoAddMargin": 0,
      "leverageSysUpdatedTime": "",
      "mmrSysUpdatedTime": "1698293363950",
      "seq": 15885756793,
      "isReduceOnly": false
    },
    "timestamp": 1709836550251.0,
    "datetime": "2024-03-07T18:35:50.251Z",
    "contracts": 0.1,
    "contractsSize": null,
    "side": "long",
    "notional": 6.885,
    "leverage": 6.0,
    "unrealizedPnl": 1.792,
    "realizedPnl": null,
    "collateral": 1.1506557,
    "entryPrice": 68.85,
    "markPrice": 86.77,
    "liquidationPrice": 58.07,
    "stopLossPrice": 0.0,
    "takeProfitPrice": 0.0,
    "marginMode": null,
    "hedged": null,
    "maintenenceMargin": null,
    "maintenanceMarginPercentage": null,
    "initialMargin": 1.1475,
    "initialMarginPercentage": 0.16666666666666666,
    "marginRatio": null,
    "lastUpdateTimestamp": null,
    "lastPrice": null,
    "percentage": null
  }
]
```

**Comment by nikky78** [comment]
how do you set verbiose mode ? I still don't manage. 
I am waiting for the response like that :

```
var positions = await exchange.watchPositions();
log.Debug($"positions: {positions}");
```
but it hangs.

**Comment by nikky78** [comment]
Maybe it's the sandbox. I tried in with ccxt.py and it works, I get the position update as expected.

**Comment by carlosmiei** [comment]
@nikky78 I'm also using the sandbox.

@nikky78 As you can see in the log bybit returns empty meaning that you have no positions opened.

**Comment by nikky78** [comment]
So indeed, it receives the message, it print correctly in verbiose mode, I can see my position, although when I do that:
var positions = await exchange.watchPositions();
Console.WriteLine($"positions1: {positions}");

my position is never printed and the program hangs like it is still waiting for the information. I am opening and closing positions and the program does not stop while there is only that watch.position command and I see this when i immediatly open a position after starting the program.

ResponseBody:
{"retCode":0,"retMsg":"OK","result":{"nextPageCursor":"BTCUSDT%2C1709851861890%2C0","category":"linear","list":[{"symbol":"BTCUSDT","leverage":"10","autoAddMargin":0,"avgPrice":"67269","liqPrice":"60878.5","riskLimitValue":"2000000","takeProfit":"","positionValue":"67.269","isReduceOnly":false,"tpslMode":"Full","riskId":1,"trailingStop":"0","unrealisedPnl":"-0.04326","markPrice":"67225.74","adlRankIndicator":2,"cumRealisedPnl":"-1.0829176","positionMM":"0.36964316","createdTime":"1709729485621","positionIdx":0,"positionIM":"6.76019816","seq":8998053130,"updatedTime":"1709851861890","side":"Buy","bustPrice":"","positionBalance":"6.76019816","leverageSysUpdatedTime":"","curRealisedPnl":"-0.03699795","size":"0.001","positionStatus":"Normal","mmrSysUpdatedTime":"","stopLoss":"","tradeMode":0,"sessionAvgPrice":""}]},"retExtInfo":{},"time":1709851864039}

**Comment by nikky78** [comment]
Si you have such an issue?

**Comment by nikky78** [comment]
I am on future market actually. I just realized that I did not specify! I have this  {"options", new Dictionary<string, object>() { { "defaultType", "swap" } in additional for the exchange arguments. And I do not receive positions

**Comment by nikky78** [comment]
> @nikky78 I'm also using the sandbox.
> 
> @nikky78 As you can see in the log bybit returns empty meaning that you have no positions opened.

The empty is comes from calling bybit GET https://api-testnet.bybit.com/v5/position/list?settleCoin=USDT&category=linear 200 OK . So at initializing the await watchpositions it seems that it query the current position and then call watchPositions from the websocket. But then nothing from the websocket and the program hangs

**Comment by nikky78** [comment]
I see that it connects to WebSocket connected to wss://stream-testnet.bybit.com/v5/private
Sending message: {"op":"auth","args":["pmqm5YIZnr4aDsQ6Sl","1709918768683","4382e313108428cce56879896b322ebeeabada75d573d895aa419d156c19f759"]}
but then it's just getting info from bybit GET https://api-testnet.bybit.com/v5/user/query-api? and bybit GET https://api-testnet.bybit.com/v5/position/list?settleCoin=USDT&category=linear
But I dont see any thing after from the websocket

**Comment by nikky78** [comment]
> @nikky78 Can you enable the verbose mode and post it?
> 
> I just tested and seems to work
> 
> ```
> > ccxt@4.2.64 cli.cs
> > dotnet run --project "./cs/cli/cli.csproj" bybit WatchPositions --sandbox
> 
> /Users/cjg/Git/ccxt10/ccxt/cs/cli/Program.cs(146,13): warning CS0162: Unreachable code detected [/Users/cjg/Git/ccxt10/ccxt/cs/cli/cli.csproj]
> []
> [
>   {
>     "symbol": "LTC/USDT:USDT",
>     "id": null,
>     "info": {
>       "symbol": "LTCUSDT",
>       "leverage": "6",
>       "autoAddMargin": 0,
>       "avgPrice": "68.85",
>       "liqPrice": "58.07",
>       "riskLimitValue": "200000",
>       "takeProfit": "",
>       "positionValue": "13.77",
>       "isReduceOnly": false,
>       "tpslMode": "Full",
>       "riskId": 71,
>       "trailingStop": "0",
>       "unrealisedPnl": "3.572",
>       "markPrice": "86.71",
>       "adlRankIndicator": 2,
>       "cumRealisedPnl": "-46.08492245",
>       "positionMM": "0.14401135",
>       "createdTime": "1677168085779",
>       "positionIdx": 0,
>       "positionIM": "2.30131139",
>       "seq": 15885008639,
>       "updatedTime": "1709827200408",
>       "side": "Buy",
>       "bustPrice": "",
>       "positionBalance": "2.30131139",
>       "leverageSysUpdatedTime": "",
>       "curRealisedPnl": "-0.05839597",
>       "size": "0.2",
>       "positionStatus": "Normal",
>       "mmrSysUpdatedTime": "1698293363950",
>       "stopLoss": "",
>       "tradeMode": 0,
>       "sessionAvgPrice": "",
>       "nextPageCursor": "ETHUSDT%2C1709827200238%2C0"
>     },
>     "timestamp": 1709827200408.0,
>     "datetime": "2024-03-07T16:00:00.408Z",
>     "contracts": 0.2,
>     "contractsSize": null,
>     "side": "long",
>     "notional": 13.77,
>     "leverage": 6.0,
>     "unrealizedPnl": 3.572,
>     "realizedPnl": null,
>     "collateral": 2.30131139,
>     "entryPrice": 68.85,
>     "markPrice": 86.71,
>     "liquidationPrice": 58.07,
>     "stopLossPrice": null,
>     "takeProfitPrice": null,
>     "marginMode": null,
>     "hedged": null,
>     "maintenenceMargin": null,
>     "maintenanceMarginPercentage": null,
>     "initialMargin": 2.295,
>     "initialMarginPercentage": 0.16666666666666666,
>     "marginRatio": null,
>     "lastUpdateTimestamp": null,
>     "lastPrice": null,
>     "percentage": null
>   },
>   {
>     "symbol": "XMR/USDT:USDT",
>     "id": null,
>     "info": {
>       "symbol": "XMRUSDT",
>       "leverage": "10",
>       "autoAddMargin": 0,
>       "avgPrice": "170.925",
>       "liqPrice": "182.88",
>       "riskLimitValue": "100000",
>       "takeProfit": "",
>       "positionValue": "167.5065",
>       "isReduceOnly": false,
>       "tpslMode": "Full",
>       "riskId": 1,
>       "trailingStop": "0",
>       "unrealisedPnl": "25.3183",
>       "markPrice": "145.09",
>       "adlRankIndicator": 2,
>       "cumRealisedPnl": "9.64182005",
>       "positionMM": "5.12653644",
>       "createdTime": "1701192869040",
>       "positionIdx": 0,
>       "positionIM": "16.85199144",
>       "seq": 28075523508,
>       "updatedTime": "1709827200408",
>       "side": "Sell",
>       "bustPrice": "",
>       "positionBalance": "16.85199144",
>       "leverageSysUpdatedTime": "",
>       "curRealisedPnl": "8.85080665",
>       "size": "0.98",
>       "positionStatus": "Normal",
>       "mmrSysUpdatedTime": "",
>       "stopLoss": "",
>       "tradeMode": 0,
>       "sessionAvgPrice": ""
>     },
>     "timestamp": 1709827200408.0,
>     "datetime": "2024-03-07T16:00:00.408Z",
>     "contracts": 0.98,
>     "contractsSize": null,
>     "side": "short",
>     "notional": 167.5065,
>     "leverage": 10.0,
>     "unrealizedPnl": 25.3183,
>     "realizedPnl": null,
>     "collateral": 16.85199144,
>     "entryPrice": 170.925,
>     "markPrice": 145.09,
>     "liquidationPrice": 182.88,
>     "stopLossPrice": null,
>     "takeProfitPrice": null,
>     "marginMode": null,
>     "hedged": null,
>     "maintenenceMargin": null,
>     "maintenanceMarginPercentage": null,
>     "initialMargin": 16.75065,
>     "initialMarginPercentage": 0.1,
>     "marginRatio": null,
>     "lastUpdateTimestamp": null,
>     "lastPrice": null,
>     "percentage": null
>   },
>   {
>     "symbol": "ETH/USDT:USDT",
>     "id": null,
>     "info": {
>       "symbol": "ETHUSDT",
>       "leverage": "10",
>       "autoAddMargin": 0,
>       "avgPrice": "3782.11",
>       "liqPrice": "4141.41",
>       "riskLimitValue": "900000",
>       "takeProfit": "",
>       "positionValue": "37.8211",
>       "isReduceOnly": false,
>       "tpslMode": "Full",
>       "riskId": 11,
>       "trailingStop": "0",
>       "unrealisedPnl": "-0.7531",
>       "markPrice": "3857.42",
>       "adlRankIndicator": 2,
>       "cumRealisedPnl": "-40.5401062",
>       "positionMM": "0.21198727",
>       "createdTime": "1694787586926",
>       "positionIdx": 0,
>       "positionIM": "3.80499177",
>       "seq": 11172225697,
>       "updatedTime": "1709827200238",
>       "side": "Sell",
>       "bustPrice": "",
>       "positionBalance": "3.80499177",
>       "leverageSysUpdatedTime": "",
>       "curRealisedPnl": "0.00969504",
>       "size": "0.01",
>       "positionStatus": "Normal",
>       "mmrSysUpdatedTime": "",
>       "stopLoss": "",
>       "tradeMode": 0,
>       "sessionAvgPrice": ""
>     },
>     "timestamp": 1709827200238.0,
>     "datetime": "2024-03-07T16:00:00.238Z",
>     "contracts": 0.01,
>     "contractsSize": null,
>     "side": "short",
>     "notional": 37.8211,
>     "leverage": 10.0,
>     "unrealizedPnl": -0.7531,
>     "realizedPnl": null,
>     "collateral": 3.80499177,
>     "entryPrice": 3782.11,
>     "markPrice": 3857.42,
>     "liquidationPrice": 4141.41,
>     "stopLossPrice": null,
>     "takeProfitPrice": null,
>     "marginMode": null,
>     "hedged": null,
>     "maintenenceMargin": null,
>     "maintenanceMarginPercentage": null,
>     "initialMargin": 3.78211,
>     "initialMarginPercentage": 0.1,
>     "marginRatio": null,
>     "lastUpdateTimestamp": null,
>     "lastPrice": null,
>     "percentage": null
>   },
>   {
>     "symbol": "XRP/USD:XRP",
>     "id": null,
>     "info": {
>       "positionIdx": 0,
>       "riskId": 31,
>       "riskLimitValue": "750000",
>       "symbol": "XRPUSD",
>       "side": "Sell",
>       "size": "1",
>       "avgPrice": "0.5074",
>       "positionValue": "1.97083169",
>       "tradeMode": 0,
>       "positionStatus": "Normal",
>       "autoAddMargin": 1,
>       "adlRankIndicator": 2,
>       "leverage": "10",
>       "positionBalance": "0.57042496",
>       "markPrice": "0.6256",
>       "liqPrice": "",
>       "bustPrice": "199.9998",
>       "positionMM": "0.00005",
>       "positionIM": "0.03941663",
>       "tpslMode": "Full",
>       "takeProfit": "0.0000",
>       "stopLoss": "0.0000",
>       "trailingStop": "0.0000",
>       "unrealisedPnl": "-0.37236622",
>       "cumRealisedPnl": "0.03714892",
>       "curRealisedPnl": "0.03853953",
>       "seq": 2920329003,
>       "isReduceOnly": false,
>       "mmrSysUpdateTime": "",
>       "leverageSysUpdatedTime": "",
>       "sessionAvgPrice": "",
>       "createdTime": "1707169185250",
>       "updatedTime": "1709827200015"
>     },
>     "timestamp": 1709827200015.0,
>     "datetime": "2024-03-07T16:00:00.015Z",
>     "contracts": 1.0,
>     "contractsSize": null,
>     "side": "short",
>     "notional": 1.97083169,
>     "leverage": 10.0,
>     "unrealizedPnl": -0.37236622,
>     "realizedPnl": null,
>     "collateral": 0.57042496,
>     "entryPrice": 0.5074,
>     "markPrice": 0.6256,
>     "liquidationPrice": null,
>     "stopLossPrice": 0.0,
>     "takeProfitPrice": 0.0,
>     "marginMode": null,
>     "hedged": null,
>     "maintenenceMargin": null,
>     "maintenanceMarginPercentage": 2.5370000012532E-05,
>     "initialMargin": 0.03941663,
>     "initialMarginPercentage": 0.01999999807188,
>     "marginRatio": 0.0,
>     "lastUpdateTimestamp": null,
>     "lastPrice": null,
>     "percentage": null
>   }
> ]
>  
> 
> 
> 
> 
> 
> 
> 
> 
> [
>   {
>     "symbol": "LTC/USDT:USDT",
>     "id": null,
>     "info": {
>       "positionIdx": 0,
>       "tradeMode": 0,
>       "riskId": 71,
>       "riskLimitValue": "200000",
>       "symbol": "LTCUSDT",
>       "side": "Buy",
>       "size": "0.1",
>       "entryPrice": "68.85",
>       "sessionAvgPrice": "",
>       "leverage": "6",
>       "positionValue": "6.885",
>       "positionBalance": "1.1506557",
>       "markPrice": "86.77",
>       "positionIM": "1.1506557",
>       "positionMM": "0.07200568",
>       "takeProfit": "0",
>       "stopLoss": "0",
>       "trailingStop": "0",
>       "unrealisedPnl": "1.792",
>       "cumRealisedPnl": "-44.29669535",
>       "curRealisedPnl": "1.72983113",
>       "createdTime": "1677168085779",
>       "updatedTime": "1709836550251",
>       "tpslMode": "Full",
>       "liqPrice": "58.07",
>       "bustPrice": "",
>       "category": "linear",
>       "positionStatus": "Normal",
>       "adlRankIndicator": 2,
>       "autoAddMargin": 0,
>       "leverageSysUpdatedTime": "",
>       "mmrSysUpdatedTime": "1698293363950",
>       "seq": 15885756793,
>       "isReduceOnly": false
>     },
>     "timestamp": 1709836550251.0,
>     "datetime": "2024-03-07T18:35:50.251Z",
>     "contracts": 0.1,
>     "contractsSize": null,
>     "side": "long",
>     "notional": 6.885,
>     "leverage": 6.0,
>     "unrealizedPnl": 1.792,
>     "realizedPnl": null,
>     "collateral": 1.1506557,
>     "entryPrice": 68.85,
>     "markPrice": 86.77,
>     "liquidationPrice": 58.07,
>     "stopLossPrice": 0.0,
>     "takeProfitPrice": 0.0,
>     "marginMode": null,
>     "hedged": null,
>     "maintenenceMargin": null,
>     "maintenanceMarginPercentage": null,
>     "initialMargin": 1.1475,
>     "initialMarginPercentage": 0.16666666666666666,
>     "marginRatio": null,
>     "lastUpdateTimestamp": null,
>     "lastPrice": null,
>     "percentage": null
>   }
> ]
> ```

I think this is just coming from the initial query through the Rest API, but not from the websocket to me.

**Comment by nikky78** [comment]
Do you confirm it works for you? I've banged my head all over cause sandbox or no, swap market option or no, nothing works it seems. the program waits for the await exchange.watchPositions() instruction.

**Comment by nikky78** [comment]
any news, please?

**Comment by nikky78** [comment]
[carlosmiei](https://github.com/carlosmiei) do you have any news ?

**Comment by carlosmiei** [comment]
@nikky78 Sorry got sidetracked with some urgent issues, will try to pick this up in a few hours

**Comment by carlosmiei** [comment]
@nikky78 What's the position you have opened right now? is it linear or inverse?

**Comment by nikky78** [comment]
Linear

**Comment by nikky78** [comment]
I do not even have FetchPositions() function for ccxt.pro.bybit
![Screenshot from 2024-03-12 16-32-32](https://github.com/ccxt/ccxt/assets/29562101/388ec181-ff25-4851-b5d6-11ab0a929c93)

**Comment by carlosmiei** [comment]
@nikky78 Can you please double check it? I'm pretty sure the method exists. https://github.com/ccxt/ccxt/blob/master/cs/ccxt/wrappers/bybit.cs#L1558

**Comment by nikky78** [comment]
My bad, indeed, i was missing a ";" so it was not properly suggesting.

But yea, it prints this: (truncated)
{
    "timestamp": 1710258980667.0,
    "datetime": "2024-03-12T15:56:20.667Z",
    "contracts": 0.006,
    "contractsSize": null,
    "side": "short",
    "notional": 434.54003143,
    "leverage": 4.0,
    "unrealizedPnl": 4.09973143,
    "realizedPnl": null,
    "collateral": 108.93375413,
    "entryPrice": 72423.33857143,
    "markPrice": 71740.05,
    "liquidationPrice": 90167.0,
    "stopLossPrice": null,
    "takeProfitPrice": null,
    "marginMode": null,
    "hedged": null,
    "maintenenceMargin": null,
    "maintenanceMarginPercentage": null,
    "initialMargin": 108.635007857145,
    "initialMarginPercentage": 0.24999999999918304,
    "marginRatio": null,
    "lastUpdateTimestamp": null,
    "lastPrice": null,
    "percentage": null
  }

**Comment by carlosmiei** [comment]
@nikky78 So the problem is that `watchPositions` does not return currently opened positions or positions that you open after calling `WatchPositions`?

**Comment by nikky78** [comment]
@carlosmiei  So it seems that when one call watchPositions(), it first retrieve the current open positions with fetchPositions trhough Rest. I can see that the call is properly made. But then I feels like it waits to receive at least one message from the websocket, and it does not. Even if opening and closing positions. Tht's when it hangs

**Comment by carlosmiei** [comment]
@nikky78 But you do get the "first" snapshot return right?

**Comment by nikky78** [comment]
@carlosmiei any news ?

**Comment by nikky78** [comment]
@carlosmiei Any news ?

**Comment by carlosmiei** [comment]
@nikky78 I'm sorry I having a hard time testing all use-cases of this issue, so far I tried:

- call watchPositions with previously open positions  (the first return went ok)
- modify the current positions (got the update)
- open a new position (got the update)
- close a position (did not get an update? have to check this)

I will run a few more tests and I will let you know

**Comment by nikky78** [comment]
@carlosmiei try with no open position at start also

**Comment by nikky78** [comment]
@carlosmiei perfect! tahnks for your help!

**Comment by carlosmiei** [comment]
@nikky78 Have you had the chance to test the latest version?

**Comment by nikky78** [comment]
Hi. Just did, same:
You can see that I'm Fetching first my open positions. It prints properly position: ...
But then it awaits the update from the websocket. And despite me opening, closing, it does not print position1, and hangs.

![image](https://github.com/ccxt/ccxt/assets/29562101/d5f3d4b7-45cc-4848-90e9-14536140e112)

**Comment by carlosmiei** [comment]
@nikky78 Ok You need to run the `Watch` methods inside a while (true) {} loop, otherwise you will only get the first update and the execution context will move to the next statement.

Example:

```C#
    public static async Task runBackground(ccxt.Exchange exchange)
    {

        while (true)
        {
            try
            {
                var trades = await exchange.WatchPositions("BTC/USDT");
                Console.WriteLine("Got Postion");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                break;
            }
        }
    }
```

and then you can call it in the background by doing;
```C#
        Task.Run(async () =>
            {
                await runBackground(exchange);
            });
```

**Comment by shiftdeloff** [comment]
> @nikky78Извините, мне было трудно протестировать все варианты использования этой проблемы, я попробовал:
> 
>     * вызвать watchPositions с ранее открытыми позициями (первый возврат прошел нормально)
> 
>     * изменить текущие позиции (получил обновление)
> 
>     * открыть новую позицию (получил обновление)
> 
>     * закрыть позицию (не получили обновления? нужно проверить это)
> 
> 
> Я проведу еще несколько тестов и дам вам знать

Now i have the same problem in Python, I don’t receive status updates for a closed position(everything else is ok, as you wrote), how can I fix this? The library has been updated. Here are the logs:

fetch Response: bybit GET https://api-testnet.bybit.com/v5/position/list?category=inverse 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '126', 'Connection': 'keep-alive', 'Date': 'Thu, 28 Mar 2024 09:14:57 GMT', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1711617297719', 'Ret_code': '0', 'Traceid': '32e8aa7854670aa803ae0c05fd2fdfb2', 'Timenow': '1711617297722', 'Server': 'Openresty', 'x-cld-src': 'Loc-A', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 b99111dfd026a3c99d0e66063beb0544.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA60-P5', 'X-Amz-Cf-Id': 'DISy6DY4W3hiEEUWdffF2GWhZzd2_TXO3fLq4SvXrjZGwR3vMEJkMQ=='} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"list":[],"nextPageCursor":"","category":"inverse"},"retExtInfo":{},"time":1711617297722}
12:14:55,873351 DEBUG: GET https://api-testnet.bybit.com/v5/position/list?category=inverse, Response: 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '126', 'Connection': 'keep-alive', 'Date': 'Thu, 28 Mar 2024 09:14:57 GMT', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1711617297719', 'Ret_code': '0', 'Traceid': '32e8aa7854670aa803ae0c05fd2fdfb2', 'Timenow': '1711617297722', 'Server': 'Openresty', 'x-cld-src': 'Loc-A', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 b99111dfd026a3c99d0e66063beb0544.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA60-P5', 'X-Amz-Cf-Id': 'DISy6DY4W3hiEEUWdffF2GWhZzd2_TXO3fLq4SvXrjZGwR3vMEJkMQ=='} {"retCode":0,"retMsg":"OK","result":{"list":[],"nextPageCursor":"","category":"inverse"},"retExtInfo":{},"time":1711617297722}
12:14:55,874415 INFO: ----------...connected to positions...----------     #here we connected first time
12:14:55,874415 INFO: Position is empty
12:14:55,874415 INFO: Entry price: None
12:14:55,875417 INFO: position: False
2024-03-28T09:14:56.913Z sending {'op': 'subscribe', 'req_id': 2, 'args': ['position']}
2024-03-28T09:14:57.142Z message {"req_id":"2","success":true,"ret_msg":"","op":"subscribe","conn_id":"cno3fi5daugt7mgdqvtg-qzzm"}
2024-03-28T09:15:00.308Z message {"id":"100552686_position_1711617302159","topic":"position","creationTime":1711617302159,"data":[{"positionIdx":0,"tradeMode":0,"riskId":1,"riskLimitValue":"2000000","symbol":"BTCUSDT","side":"Buy","size":"0.01","entryPrice":"70799","sessionAvgPrice":"","leverage":"1","positionValue":"707.99","positionBalance":"0","markPrice":"70801.18","positionIM":"707.99","positionMM":"3.53995","takeProfit":"0","stopLoss":"0","trailingStop":"0","unrealisedPnl":"0.0218","cumRealisedPnl":"-174.18323567","curRealisedPnl":"-0.3893945","createdTime":"1709481492625","updatedTime":"1711617302156","tpslMode":"Full","liqPrice":"","bustPrice":"","category":"linear","positionStatus":"Normal","adlRankIndicator":2,"autoAddMargin":0,"leverageSysUpdatedTime":"","mmrSysUpdatedTime":"","seq":9084791343,"isReduceOnly":false}]}
12:15:00,309748 INFO: ----------...connected to positions...----------    #create order and see incorrect status 
12:15:00,310746 INFO: position: True
12:15:00,310746 INFO: Entry price when position is not empty: 70799.0    #must be None (if i use fetch_positions, it would be                None now)
2024-03-28T09:15:06.239Z message {"id":"100552686_position_1711617308090","topic":"position","creationTime":1711617308089,"data":[{"positionIdx":0,"tradeMode":0,"riskId":1,"riskLimitValue":"2000000","symbol":"BTCUSDT","side":"","size":"0","entryPrice":"0","sessionAvgPrice":"","leverage":"1","positionValue":"0","positionBalance":"0","markPrice":"70779.3","positionIM":"0","positionMM":"0","takeProfit":"0","stopLoss":"0","trailingStop":"0","unrealisedPnl":"0","cumRealisedPnl":"-174.78351412","curRealisedPnl":"0","createdTime":"1709481492625","updatedTime":"1711617308086","tpslMode":"Full","liqPrice":"0","bustPrice":"","category":"linear","positionStatus":"Normal","adlRankIndicator":0,"autoAddMargin":0,"leverageSysUpdatedTime":"","mmrSysUpdatedTime":"","seq":9084791637,"isReduceOnly":false}]}
12:15:06,240633 INFO: ----------...connected to positions...----------  #close position
12:15:06,240633 INFO: position: True
2024-03-28T09:15:08.283Z message {"id":"100552686_position_1711617310134","topic":"position","creationTime":1711617310134,"data":[{"positionIdx":0,"tradeMode":0,"riskId":1,"riskLimitValue":"2000000","symbol":"BTCUSDT","side":"","size":"0","entryPrice":"0","sessionAvgPrice":"","leverage":"1","positionValue":"0","positionBalance":"0","markPrice":"70779.3","positionIM":"0","positionMM":"0","takeProfit":"0","stopLoss":"0","trailingStop":"0","unrealisedPnl":"0","cumRealisedPnl":"-174.78351412","curRealisedPnl":"0","createdTime":"1709481492625","updatedTime":"1711617310132","tpslMode":"Full","liqPrice":"0","bustPrice":"","category":"linear","positionStatus":"Normal","adlRankIndicator":0,"autoAddMargin":0,"leverageSysUpdatedTime":"","mmrSysUpdatedTime":"","seq":9084791637,"isReduceOnly":false}]}
12:15:08,284059 INFO: ----------...connected to positions...----------   #still no correct update...
12:15:08,284059 INFO: position: True
2024-03-28T09:15:15.286Z sending {'req_id': 6, 'op': 'ping'}
2024-03-28T09:15:15.515Z message {"req_id":"6","op":"pong","args":["1711617317367"],"conn_id":"cno3fi5daugt7mgdqvtg-qzzm"}
2024-03-28T09:15:35.307Z sending {'req_id': 7, 'op': 'ping'}
2024-03-28T09:15:35.536Z message {"req_id":"7","op":"pong","args":["1711617337388"],"conn_id":"cno3fi5daugt7mgdqvtg-qzzm"}

**Comment by carlosmiei** [comment]
@shiftdeloff I will check it and let you know

**Comment by shiftdeloff** [comment]
> @shiftdeloff I will check it and let you know

I checked it on the OKX and got the same thing. Moreover, the fetch method works fine on both exchanges...
But I don’t like the fetch method, and when I tested it now, I had problems with manually closing a position on the exchange (closed only on the 3rd or 4th attempt), receiving a warning from Okx about “abnormal network conditions” or something like that , perhaps due to the frequency of checking the position using the fetch method(even with a sleep of 1 second), so of course I would like to use the watch method..
Logs from Okx:
2024-03-28T12:30:36.192Z message pong
2024-03-28T12:30:36.197Z message {"event":"login","msg":"","code":"0","connId":"02ce4ffc"}
2024-03-28T12:30:36.312Z sending {'op': 'subscribe', 'args': [{'channel': 'positions', 'instType': 'ANY'}]}
2024-03-28T12:30:36.628Z message {"event":"subscribe","arg":{"channel":"positions","instType":"ANY"},"connId":"02ce4ffc"}
2024-03-28T12:30:36.629Z message {"event":"channel-conn-count","channel":"positions","connCount":"1","connId":"02ce4ffc"}
2024-03-28T12:30:36.647Z message {"arg":{"channel":"positions","instType":"ANY","uid":"504676281032580739"},"data":[]}
15:30:36,647025 INFO: ----------...connected to positions...---------- #before creating order
15:30:36,647025 INFO: Position is empty
15:30:36,648024 INFO: Entry price: None
15:30:36,648024 INFO: position: False
2024-03-28T12:30:55.884Z sending ping
2024-03-28T12:30:56.196Z message pong
2024-03-28T12:30:58.470Z message {"arg":{"channel":"positions","instType":"ANY","uid":"504676281032580739"},"data":[{"adl":"1","availPos":"","avgPx":"70614.8","baseBal":"","baseBorrowed":"","baseInterest":"","bePx":"70685.45012506253","bizRefId":"","bizRefType":"","cTime":"1711629060586","ccy":"USDT","closeOrderAlgo":[],"deltaBS":"","deltaPA":"","fee":"-0.0353074","fundingFee":"0","gammaBS":"","gammaPA":"","idxPx":"70586.3","imr":"","instId":"BTC-USDT-SWAP","instType":"SWAP","interest":"","last":"70614.8","lever":"1","liab":"","liabCcy":"","liqPenalty":"0","liqPx":"0","margin":"70.6148","markPx":"70606.9","mgnMode":"isolated","mgnRatio":"222.2222222222222","mmr":"0.2824275999999999","notionalUsd":"70.57159655","optVal":"","pTime":"1711629060590","pendingCloseOrdLiabVal":"","pnl":"0","pos":"1","posCcy":"","posId":"693526074638045442","posSide":"net","quoteBal":"","quoteBorrowed":"","quoteInterest":"","realizedPnl":"-0.0353074","spotInUseAmt":"","spotInUseCcy":"","thetaBS":"","thetaPA":"","tradeId":"874409440","uTime":"1711629060586","upl":"-0.0079000000000087","uplLastPx":"0","uplRatio":"-0.000111874564539","uplRatioLastPx":"0","usdPx":"","vegaBS":"","vegaPA":""}]}
15:30:58,470697 INFO: ----------...connected to positions...---------- #create order here...
15:30:58,470697 INFO: position: True
15:30:58,470697 INFO: Entry price when position is not empty: 70614.8
2024-03-28T12:31:00.370Z message {"arg":{"channel":"positions","instType":"ANY","uid":"504676281032580739"},"data":[{"adl":"1","availPos":"","avgPx":"70614.8","baseBal":"","baseBorrowed":"","baseInterest":"","bePx":"70685.45012506253","bizRefId":"","bizRefType":"","cTime":"1711629060586","ccy":"USDT","closeOrderAlgo":[],"deltaBS":"","deltaPA":"","fee":"-0.0353074","fundingFee":"0","gammaBS":"","gammaPA":"","idxPx":"70580.0","imr":"","instId":"BTC-USDT-SWAP","instType":"SWAP","interest":"","last":"70610.3","lever":"1","liab":"","liabCcy":"","liqPenalty":"0","liqPx":"0","margin":"70.6148","markPx":"70603.1","mgnMode":"isolated","mgnRatio":"222.2222222222222","mmr":"0.2824124","notionalUsd":"70.56850448100002","optVal":"","pTime":"1711629062491","pendingCloseOrdLiabVal":"","pnl":"0","pos":"1","posCcy":"","posId":"693526074638045442","posSide":"net","quoteBal":"","quoteBorrowed":"","quoteInterest":"","realizedPnl":"-0.0353074","spotInUseAmt":"","spotInUseCcy":"","thetaBS":"","thetaPA":"","tradeId":"874409440","uTime":"1711629060586","upl":"-0.0116999999999971","uplLastPx":"-0.0045","uplRatio":"-0.0001656876462157","uplRatioLastPx":"-0.0000637260177753","usdPx":"","vegaBS":"","vegaPA":""}]}
15:31:00,372297 INFO: ----------...connected to positions...----------
15:31:00,372297 INFO: position: True
15:31:00,372297 INFO: Entry price when position is not empty: 70614.8
2024-03-28T12:31:05.377Z message {"arg":{"channel":"positions","instType":"ANY","uid":"504676281032580739"},"data":[{"adl":"1","availPos":"","avgPx":"70614.8","baseBal":"","baseBorrowed":"","baseInterest":"","bePx":"70685.45012506253","bizRefId":"","bizRefType":"","cTime":"1711629060586","ccy":"USDT","closeOrderAlgo":[],"deltaBS":"","deltaPA":"","fee":"-0.0353074","fundingFee":"0","gammaBS":"","gammaPA":"","idxPx":"70539.3","imr":"","instId":"BTC-USDT-SWAP","instType":"SWAP","interest":"","last":"70608.8","lever":"1","liab":"","liabCcy":"","liqPenalty":"0","liqPx":"0","margin":"70.6148","markPx":"70592.8","mgnMode":"isolated","mgnRatio":"222.22222222222214","mmr":"0.2823712","notionalUsd":"70.56173916800002","optVal":"","pTime":"1711629067495","pendingCloseOrdLiabVal":"","pnl":"0","pos":"1","posCcy":"","posId":"693526074638045442","posSide":"net","quoteBal":"","quoteBorrowed":"","quoteInterest":"","realizedPnl":"-0.0353074","spotInUseAmt":"","spotInUseCcy":"","thetaBS":"","thetaPA":"","tradeId":"874409440","uTime":"1711629060586","upl":"-0.022","uplLastPx":"-0.006","uplRatio":"-0.0003115494202348","uplRatioLastPx":"-0.0000849680237004","usdPx":"","vegaBS":"","vegaPA":""}]}
15:31:05,379266 INFO: ----------...connected to positions...----------
15:31:05,379266 INFO: position: True
15:31:05,379266 INFO: Entry price when position is not empty: 70614.8
2024-03-28T12:31:10.375Z message {"arg":{"channel":"positions","instType":"ANY","uid":"504676281032580739"},"data":[{"adl":"1","availPos":"","avgPx":"70614.8","baseBal":"","baseBorrowed":"","baseInterest":"","bePx":"70685.45012506253","bizRefId":"","bizRefType":"","cTime":"1711629060586","ccy":"USDT","closeOrderAlgo":[],"deltaBS":"","deltaPA":"","fee":"-0.0353074","fundingFee":"0","gammaBS":"","gammaPA":"","idxPx":"70516.5","imr":"","instId":"BTC-USDT-SWAP","instType":"SWAP","interest":"","last":"70565.7","lever":"1","liab":"","liabCcy":"","liqPenalty":"0","liqPx":"0","margin":"70.6148","markPx":"70574.2","mgnMode":"isolated","mgnRatio":"222.22222222222214","mmr":"0.2822968","notionalUsd":"70.543147352","optVal":"","pTime":"1711629072496","pendingCloseOrdLiabVal":"","pnl":"0","pos":"1","posCcy":"","posId":"693526074638045442","posSide":"net","quoteBal":"","quoteBorrowed":"","quoteInterest":"","realizedPnl":"-0.0353074","spotInUseAmt":"","spotInUseCcy":"","thetaBS":"","thetaPA":"","tradeId":"874409440","uTime":"1711629060586","upl":"-0.0406000000000058","uplLastPx":"-0.0491000000000058","uplRatio":"-0.0005749502937062","uplRatioLastPx":"-0.0006953216606151","usdPx":"","vegaBS":"","vegaPA":""}]}
15:31:10,376492 INFO: ----------...connected to positions...---------- #close position...and incorrect status
15:31:10,376492 INFO: position: True
15:31:10,376998 INFO: Entry price when position is not empty: 70614.8
2024-03-28T12:31:14.829Z message {"arg":{"channel":"positions","instType":"ANY","uid":"504676281032580739"},"data":[{"adl":"","availPos":"","avgPx":"","baseBal":"","baseBorrowed":"","baseInterest":"","bePx":"","bizRefId":"","bizRefType":"","cTime":"1711629060586","ccy":"USDT","closeOrderAlgo":[],"deltaBS":"","deltaPA":"","fee":"","fundingFee":"","gammaBS":"","gammaPA":"","idxPx":"","imr":"","instId":"BTC-USDT-SWAP","instType":"SWAP","interest":"","last":"","lever":"","liab":"","liabCcy":"","liqPenalty":"","liqPx":"","margin":"","markPx":"","mgnMode":"isolated","mgnRatio":"","mmr":"0","notionalUsd":"","optVal":"","pTime":"1711629076951","pendingCloseOrdLiabVal":"","pnl":"","pos":"0","posCcy":"","posId":"693526074638045442","posSide":"net","quoteBal":"","quoteBorrowed":"","quoteInterest":"","realizedPnl":"","spotInUseAmt":"","spotInUseCcy":"","thetaBS":"","thetaPA":"","tradeId":"874409589","uTime":"1711629076888","upl":"","uplLastPx":"","uplRatio":"","uplRatioLastPx":"","usdPx":"","vegaBS":"","vegaPA":""}]}
15:31:14,831477 INFO: ----------...connected to positions...----------
15:31:14,832493 INFO: position: True
15:31:14,832493 INFO: Entry price when position is not empty: 70614.8
2024-03-28T12:31:15.895Z sending ping
2024-03-28T12:31:16.215Z message pong
2024-03-28T12:31:35.914Z sending ping              #ping pong until the universe dies.... :)

**Comment by shiftdeloff** [comment]
> @shiftdeloff I will check it and let you know

how is it going? 
I think I found the same problem with the watch_orders method (it also returns true after the order is cancelled) please check that too if you can...

bybit logs:

2024-04-11T18:03:34.552Z message {"success":true,"ret_msg":"","op":"auth","conn_id":"cno3fi5daugt7mgdqvtg-1343p"}
2024-04-11T18:03:34.575Z sending {'op': 'subscribe', 'req_id': 2, 'args': ['order']}
2024-04-11T18:03:34.804Z message {"req_id":"2","success":true,"ret_msg":"","op":"subscribe","conn_id":"cno3fi5daugt7mgdqvtg-1343p"}
2024-04-11T18:03:49.379Z message {"topic":"order","id":"100552686_BTCUSDT_9122399925","creationTime":1712858630778,"data":[{"category":"linear","symbol":"BTCUSDT","orderId":"12eb49e9-5283-4bdb-a967-b17e6e7fc50d","orderLinkId":"","blockTradeId":"","side":"Buy","positionIdx":0,"orderStatus":"New","cancelType":"UNKNOWN","rejectReason":"EC_NoError","timeInForce":"GTC","isLeverage":"","price":"69151.4","qty":"0.001","avgPrice":"","leavesQty":"0.001","leavesValue":"69.1514","cumExecQty":"0","cumExecValue":"0","cumExecFee":"0","orderType":"Limit","stopOrderType":"","orderIv":"","triggerPrice":"","takeProfit":"","stopLoss":"","triggerBy":"","tpTriggerBy":"","slTriggerBy":"","triggerDirection":0,"placeType":"","lastPriceOnCreated":"70305.8","closeOnTrigger":false,"reduceOnly":false,"smpGroup":0,"smpType":"None","smpOrderId":"","slLimitPrice":"0","tpLimitPrice":"0","tpslMode":"UNKNOWN","createType":"CreateByUser","marketUnit":"","createdTime":"1712858603220","updatedTime":"1712858630777","feeCurrency":""}]}        
21:03:49,380652 INFO: ----------...connected to order...----------
21:03:49,380652 INFO: order: True
2024-04-11T18:03:54.340Z sending {'req_id': 4, 'op': 'ping'}
2024-04-11T18:03:54.857Z message {"req_id":"4","op":"pong","args":["1712858636242"],"conn_id":"cno3fi5daugt7mgdqvtg-1343p"}
2024-04-11T18:04:01.896Z message {"topic":"order","id":"100552686_BTCUSDT_9122400204","creationTime":1712858643572,"data":[{"category":"linear","symbol":"BTCUSDT","orderId":"12eb49e9-5283-4bdb-a967-b17e6e7fc50d","orderLinkId":"","blockTradeId":"","side":"Buy","positionIdx":0,"orderStatus":"Cancelled","cancelType":"CancelByUser","rejectReason":"EC_PerCancelRequest","timeInForce":"GTC","isLeverage":"","price":"69151.4","qty":"0.001","avgPrice":"","leavesQty":"0","leavesValue":"0","cumExecQty":"0","cumExecValue":"0","cumExecFee":"0","orderType":"Limit","stopOrderType":"","orderIv":"","triggerPrice":"","takeProfit":"","stopLoss":"","triggerBy":"","tpTriggerBy":"","slTriggerBy":"","triggerDirection":0,"placeType":"","lastPriceOnCreated":"70305.8","closeOnTrigger":false,"reduceOnly":false,"smpGroup":0,"smpType":"None","smpOrderId":"","slLimitPrice":"0","tpLimitPrice":"0","tpslMode":"UNKNOWN","createType":"CreateByUser","marketUnit":"","createdTime":"1712858603220","updatedTime":"1712858643570","feeCurrency":""}]}
21:04:01,897172 INFO: ----------...connected to order...----------
21:04:01,898177 INFO: order: True
2024-04-11T18:04:14.342Z sending {'req_id': 6, 'op': 'ping'}
2024-04-11T18:04:14.568Z message {"req_id":"6","op":"pong","args":["1712858656244"],"conn_id":"cno3fi5daugt7mgdqvtg-1343p"}

**Comment by shiftdeloff** [comment]
> @shiftdeloff I will check it and let you know

how is it going? 
I think I found the same problem with the watch_orders method (it also returns true after the order is cancelled) please check that too if you can...

bybit logs:

2024-04-11T18:03:34.552Z message {"success":true,"ret_msg":"","op":"auth","conn_id":"cno3fi5daugt7mgdqvtg-1343p"}
2024-04-11T18:03:34.575Z sending {'op': 'subscribe', 'req_id': 2, 'args': ['order']}
2024-04-11T18:03:34.804Z message {"req_id":"2","success":true,"ret_msg":"","op":"subscribe","conn_id":"cno3fi5daugt7mgdqvtg-1343p"}
2024-04-11T18:03:49.379Z message {"topic":"order","id":"100552686_BTCUSDT_9122399925","creationTime":1712858630778,"data":[{"category":"linear","symbol":"BTCUSDT","orderId":"12eb49e9-5283-4bdb-a967-b17e6e7fc50d","orderLinkId":"","blockTradeId":"","side":"Buy","positionIdx":0,"orderStatus":"New","cancelType":"UNKNOWN","rejectReason":"EC_NoError","timeInForce":"GTC","isLeverage":"","price":"69151.4","qty":"0.001","avgPrice":"","leavesQty":"0.001","leavesValue":"69.1514","cumExecQty":"0","cumExecValue":"0","cumExecFee":"0","orderType":"Limit","stopOrderType":"","orderIv":"","triggerPrice":"","takeProfit":"","stopLoss":"","triggerBy":"","tpTriggerBy":"","slTriggerBy":"","triggerDirection":0,"placeType":"","lastPriceOnCreated":"70305.8","closeOnTrigger":false,"reduceOnly":false,"smpGroup":0,"smpType":"None","smpOrderId":"","slLimitPrice":"0","tpLimitPrice":"0","tpslMode":"UNKNOWN","createType":"CreateByUser","marketUnit":"","createdTime":"1712858603220","updatedTime":"1712858630777","feeCurrency":""}]}        
21:03:49,380652 INFO: ----------...connected to order...----------
21:03:49,380652 INFO: order: True
2024-04-11T18:03:54.340Z sending {'req_id': 4, 'op': 'ping'}
2024-04-11T18:03:54.857Z message {"req_id":"4","op":"pong","args":["1712858636242"],"conn_id":"cno3fi5daugt7mgdqvtg-1343p"}
2024-04-11T18:04:01.896Z message {"topic":"order","id":"100552686_BTCUSDT_9122400204","creationTime":1712858643572,"data":[{"category":"linear","symbol":"BTCUSDT","orderId":"12eb49e9-5283-4bdb-a967-b17e6e7fc50d","orderLinkId":"","blockTradeId":"","side":"Buy","positionIdx":0,"orderStatus":"Cancelled","cancelType":"CancelByUser","rejectReason":"EC_PerCancelRequest","timeInForce":"GTC","isLeverage":"","price":"69151.4","qty":"0.001","avgPrice":"","leavesQty":"0","leavesValue":"0","cumExecQty":"0","cumExecValue":"0","cumExecFee":"0","orderType":"Limit","stopOrderType":"","orderIv":"","triggerPrice":"","takeProfit":"","stopLoss":"","triggerBy":"","tpTriggerBy":"","slTriggerBy":"","triggerDirection":0,"placeType":"","lastPriceOnCreated":"70305.8","closeOnTrigger":false,"reduceOnly":false,"smpGroup":0,"smpType":"None","smpOrderId":"","slLimitPrice":"0","tpLimitPrice":"0","tpslMode":"UNKNOWN","createType":"CreateByUser","marketUnit":"","createdTime":"1712858603220","updatedTime":"1712858643570","feeCurrency":""}]}
21:04:01,897172 INFO: ----------...connected to order...----------
21:04:01,898177 INFO: order: True
2024-04-11T18:04:14.342Z sending {'req_id': 6, 'op': 'ping'}
2024-04-11T18:04:14.568Z message {"req_id":"6","op":"pong","args":["1712858656244"],"conn_id":"cno3fi5daugt7mgdqvtg-1343p"}

**Comment by kronaegor** [comment]
Hi! Did anyone solve this problem with watch_position?

**Comment by carlosmiei** [comment]
@kronaegor Is  it still happening? If so can you please opena new GH issue?

**Comment by kronaegor** [comment]
> [@kronaegor](https://github.com/kronaegor) Is it still happening? If so can you please opena new GH issue?

https://github.com/ccxt/ccxt/issues/27971
