### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#27001]
### Operating System

n/a

### Programming Language

C#

### CCXT Version

4.5.8

### Description

based on https://github.com/ccxt/ccxt/issues/26924#issuecomment-3381577894

```
One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.) (TradingBot.DataCollector.DataCollector)System.AggregateException: One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.)
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at ccxt.Exchange.WebSocketClient.Receiving(ClientWebSocket webSocket) in C:\Users\<user>\source\repos\ccxt\cs\ccxt\ws\Client.cs:line 370
   --- End of inner exception stack trace ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription) in C:\Users\<user>\source\repos\ccxt\cs\ccxt\ws\Exchange.WsBridge.cs:line 260
   at ccxt.pro.okx.watchTradesForSymbols(Object symbols, Object since, Object limit, Object parameters) in C:\Users\<user>\source\repos\ccxt\cs\ccxt\exchanges\pro\okx.cs:line 223
   at ccxt.Exchange.WatchTradesForSymbols(List`1 symbols, Nullable`1 since2, Nullable`1 limit2, Dictionary`2 parameters) in C:\Users\<user>\source\repos\ccxt\cs\ccxt\base\Exchange.Wrappers.cs:line 87
```

**Comment by ttodua** [comment]
@Alert101 
as it's hard for me to reproduce the issue, per my assumption I've pushed a potential fix, but wanted (if possible) you looked into that.
here is the PR linked above my comment. you can see changed file there. if you are able to build .dll file from source code itself (see instructions in the bottom of this post) and you could test it, would be nice. 
with that version, you would need to set (which is by defeault `false` now), eg:
```
var exchange =  new ccxt.pro.okx(); 
exchange.options.ws.nativeKeepAlive = true;  // do this for every exchange you use
```
and then check if those errors will go away or not.

______
- to build your own dll, download https://github.com/ttodua/ccxt/archive/refs/heads/option-cs-keepalive1.zip
- after unzipping, in main directory, run `dotnet build cs/ccxt.sln`
- use the generated `.dll` in your project

**Comment by alert101** [comment]
> 
> ```
> var exchange =  new ccxt.pro.okx(); 
> exchange.options.ws.nativeKeepAlive = true;  // do this for every exchange you use
> ```
> 

I'll take a look at this tonight.

**Comment by alert101** [comment]
I've made the changes and am running all WS exchanges with nativeKeepAlive = true. Will report back tomorrow.

**Comment by alert101** [comment]
@ttodua Unfortunately I'm still receiving those same errors on different exchanges.

**Comment by alert101** [comment]
@ttodua ccxt.pro.phemex seems to give this error almost immediately (within a minute or two). Here's a sample code that throws the exception after a short wait. Used ccxt 4.5.10 and .NET 9 for the test.

Note: This happens with other exchanges as well, but only after hours of running.

EDIT: Updated code with a try/catch. Whatever is the underlying cause, just waiting for a few seconds fixes the issue, eg. the connection is live again. However with Phemex this happens intermittently. Just let it run and it happens again after a short while.

```
using ccxt;

string exchangeName = "ccxt.pro.phemex";
List<string> symbols = ["BTC/USDT", "BTC/USDT:USDT", "BTC/USDC:USDC", "ETH/USDT", "ETH/USDT:USDT", "ETH/USDC:USDC"];
List<Task> tasks = [];

Console.WriteLine($"{exchangeName} test");

var exchange = Exchange.DynamicallyCreateInstance(exchangeName);
Console.WriteLine($"{exchangeName} initialized");

await exchange.LoadMarkets().ConfigureAwait(false);

var marketsLoaded = await exchange.loadMarkets(true).ConfigureAwait(false);

Dictionary<string, object> dict = marketsLoaded as Dictionary<string, object>;

foreach (KeyValuePair<string, object> market in dict)
{
    var mi = new MarketInterface(market.Value);
    if(mi.active.Equals(true) && symbols.Contains(market.Key))
    {
        Console.WriteLine($"{market.Key} is active, watching");

        tasks.Add(WatchPair(exchange, market.Key));
    }
}

async Task WatchPair(Exchange exchange, string market)
{
    while (true)
    {
        try
        {
            var trades = await exchange.WatchTrades(market).ConfigureAwait(false);
            Console.WriteLine(trades.Count);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error watching {market} on {exchangeName}: {ex.Message}");
            await Task.Delay(5000);
        }
    }
}

await Task.WhenAll(tasks).ConfigureAwait(false);
```
