### ISSUE TITLE
okex GETS yield `RequestTimeout`

### ISSUE THREAD

**Issue by benediamond** [ccxt/ccxt#3067]
- OS: Mac OS High Sierra 10.13.4
- Programming Language version: Python 3.6.3
- CCXT version: 1.13.95
- Exchange: OKEX
- Method: `load_markets`

The HTTP request methods on OKEX appear to time out. For example:
```python
>>> okex = ccxt.okex()
>>> okex.verbose = True
>>> okex.load_markets()

Request: GET https://www.okex.com/v2/markets/products.do {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 294, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.okex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 357, in fetch
    proxies=self.proxies
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.okex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 875, in load_markets
    markets = self.fetch_markets()
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/okex.py", line 58, in fetch_markets
    markets = super(okex, self).fetch_markets()
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 156, in fetch_markets
    response = self.webGetMarketsProducts()
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 306, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 367, in fetch
    self.raise_error(RequestTimeout, method, url, e)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: okex GET https://www.okex.com/v2/markets/products.do HTTPSConnectionPool(host='www.okex.com', port=443): Read timed out. (read timeout=10)
```

I'm happy to dig further into this, but if an obvious explanation occurs to anyone...? This has occurred on multiple computers / IP addresses. Thanks for your time.

**Comment by kroitor** [comment]
> I'm happy to dig further into this, but if an obvious explanation occurs to anyone...? This has occurred on multiple computers / IP addresses. Thanks for your time.

Your version is too old ) This has been fixed a few days ago. OKEX changed their web URLs. Just update to most recent version of CCXT and you'll be fine.

Duplicates:
- https://github.com/ccxt/ccxt/issues/2980
- https://github.com/ccxt/ccxt/issues/2977
- https://github.com/ccxt/ccxt/issues/2972
- ...

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues?utf8=%E2%9C%93&q=okex

**Comment by benediamond** [comment]
My apologies @kroitor, thanks for your work.

**Comment by Umbralith** [comment]
I updated, but I still get a timeout when I call fetch_balance()

**Comment by kroitor** [comment]
@Umbralith what's your current version of ccxt?

```Python
import ccxt
print ccxt.__version__
```

?
