### ISSUE TITLE
PHP binance fetch_order  - Mysticism low grade

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#6196]
- OS: Ubuntu 18.04
- Programming Language version: php 7.2
- CCXT version: LAST (27.11.2019 download master) 
- Exchange: binance
- Method: fetch_order

I get some sort of mysticism of low grade, I'm trying to get an order from him id ( 839167213 ) 

```
   public function getOrder(int $id)
    {
        $order = null;
        $this->logger->info("Get order id: " . $id);
        dump($id,$this->symbol);
        $order_open = $this->interface->fetch_order($id,$this->symbol);
        dump($order_open);
        try {
            $order_open = $this->interface->fetch_order($id,$this->symbol);
            $order = $this->orderNormalizer($order_open);
        } catch (\Exception $e) {
            $this->logger->error($e->getLine().' '.$e->getFile().' '.$e->getMessage());
            exit();
        }
        return $order;
    }
```

1 dump:

> 839167213
"BTC/USDT"

2 dump
```
array:17 [
  "info" => array:18 [
    "symbol" => "BTCUSDT"
    "orderId" => 839167213
    "orderListId" => -1
    "clientOrderId" => "PsywnsTpVO0wG0bQrxIVjL"
    "price" => "6835.99000000"
    "origQty" => "0.00292600"
    "executedQty" => "0.00000000"
    "cummulativeQuoteQty" => "0.00000000"
    "status" => "CANCELED"
    "timeInForce" => "GTC"
    "type" => "LIMIT"
    "side" => "BUY"
    "stopPrice" => "0.00000000"
    "icebergQty" => "0.00000000"
    "time" => 1574845753279
    "updateTime" => 1574855033487
    "isWorking" => true
    "origQuoteOrderQty" => "0.00000000"
  ]
  "id" => "839167213"
  "timestamp" => 1574845753279
  "datetime" => "2019-11-27T09:09:13.279Z"
  "lastTradeTimestamp" => null
  "symbol" => "BTC/USDT"
  "type" => "limit"
  "side" => "buy"
  "price" => 6835.99
  "amount" => 0.002926
  "cost" => 0.0
  "average" => null
  "filled" => 0.0
  "remaining" => 0.002926
  "status" => "canceled"
  "fee" => null
  "trades" => null
]

```
everything goes well at first, but when I repeat this request a couple of times at some point I get an error

1 dump: 
`839167213
"BTC/USDT"
`

In binance.php line 1411:
                                                      

>   [ccxt\OrderNotFound]                                
>   binance {"code":-2011,"msg":"Unknown order sent."}  

trace
> Exception trace:
>   at phar:///home/master/NextSteep/binance/src/Lib/ccxt.phar/php/binance.php:1411
>  ccxt\binance->handle_errors() at phar:///home/master/NextSteep/binance/src/Lib/ccxt.phar/php/base/Exchange.php:1392
>  ccxt\Exchange->fetch() at phar:///home/master/NextSteep/binance/src/Lib/ccxt.phar/php/base/Exchange.php:1175
>  ccxt\Exchange->fetch2() at phar:///home/master/NextSteep/binance/src/Lib/ccxt.phar/php/binance.php:1424
>  ccxt\binance->request() at n/a:n/a
>  call_user_func_array() at phar:///home/master/NextSteep/binance/src/Lib/ccxt.phar/php/base/Exchange.php:2394
>  ccxt\Exchange->__call() at phar:///home/master/NextSteep/binance/src/Lib/ccxt.phar/php/binance.php:852
>  ccxt\binance->fetch_order() at /home/master/NextSteep/binance/src/Exchange/Exchange.php:159
>  App\Exchange\Exchange->getOrder()

Can someone tell me on this issue why this happens I’m a little confused, the exchange simply stops giving the order that it has after a certain number of requests - I cannot identify whose side the problem is

**Comment by StasToken** [comment]
and so I added a delay between requests of 5 seconds but I still get this error

**Comment by kroitor** [comment]
@StasToken c

1. Can you plz show your instantiation code? 
2. Do you use the rate-limiter? https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
3. Why would you want to do the same request twice here:
```PHP
        $order_open = $this->interface->fetch_order($id,$this->symbol);  // ←----- #1
        dump($order_open);
        try {
            $order_open = $this->interface->fetch_order($id,$this->symbol);  // ←----- #2
```
?

**Comment by kroitor** [comment]
@StasToken does this work for you:

```PHP
include 'ccxt.php';

date_default_timezone_set('UTC');

$id = 'binance'; // edit this line

// ----------------------------------------------------------------------------

// instantiate the exchange by id
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class(array(

    // some exchanges may require additional API credentials
    'apiKey' => 'YOUR_API_KEY', // edit this line
    'secret' => 'YOUR_SECRET', // edit this line

    // this is required!
    'enableRateLimit' => true, // https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

    // this is not required! uncomment only if you want to debug it
    // 'verbose' => true,

));

// ----------------------------------------------------------------------------

if ($exchange->has['fetchOrder'] === false) {

    echo $exchange->id . " does not support fetchOrder() yet\n";
    exit();

} else if ($exchange->has['fetchOrder'] === 'emulated') {

    echo $exchange->id . " fetchOrder() is 'emulated' and relies " .
        "on the `.orders` cache as described in the Manual:\n" .
        "https://github.com/ccxt/ccxt/wiki/Manual#orders-cache\n";

    exit();

}

// ----------------------------------------------------------------------------

if ($exchange->has['fetchOrder'] === true) {

    $order_id = '839167213'; // edit this line
    $symbol = 'ETH/BTC'; // edit this line

    while (true) {

        try {

            $order = $exchange->fetch_order($order_id, $symbol, $params);
            echo $exchange->iso8601 ($e
            print_r($order);

        } catch (\ccxt\NetworkError $e) {

            // in case of a networking or a connectivity error instead of simply
            // printing the error message here, the application should define
            // the behavior or a recover-and-retry strategy, because networking
            // errors are temporary and occasionally happen with all exchanges
            // a retry after a while may be enough, depending on the error
            echo get_class ($e) . ': ' . $e->getMessage () . "\n";

        } catch (\ccxt\ExchangeError $e) {

            // in case of an exchange error the application should stop and signal
            // the error to the developer or to the user, human interference is
            // required to resolve an exchange error in each specific case
            echo get_class ($e) . ': ' . $e->getMessage () . "\n";

        } catch (Exception $e) {

            echo get_class ($e) . ': ' . $e->getMessage () . "\n";

        }
    }
}
```

?

**Comment by StasToken** [comment]
Your code below does not work there syntax error
Code #1 is written just for debug
I increased rate limit to 1000 and 'enableRateLimit' => true but it didn’t give effect

**Comment by kroitor** [comment]
@StasToken pardon for the typos in the snippet above, edited it, can you please retry the edited version above again?

**Comment by StasToken** [comment]
I also thought that I was making too many requests however I made a delay of 5 seconds between requests and still get such an error

**Comment by kroitor** [comment]
> however I made a delay of 5 seconds between requests and still get such an error

Because you don't show the code that sets the delay, it's hard to tell the exact cause of the problem. I suggest that you retry my snippet from above (edited it for typos) and let us know if it works for you or not.

**Comment by StasToken** [comment]
I'm afraid something is wrong with your code

> PHP Notice:  Undefined variable: params in /home/master/NextSteep/ccxt/distributor/test.php on line 54
> PHP Warning:  array_merge(): Argument #2 is not an array in /home/master/NextSteep/ccxt/distributor/php/binance.php on line 852
> PHP Warning:  array_merge(): Argument #2 is not an array in /home/master/NextSteep/ccxt/distributor/php/binance.php on line 1332
> PHP Warning:  Invalid argument supplied for foreach() in /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php on line 598
> PHP Warning:  http_build_query(): Parameter 1 expected to be Array or Object.  Incorrect value given in /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php on line 603
> ccxt\ExchangeError: binance {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."}
> PHP Notice:  Undefined variable: params in /home/master/NextSteep/ccxt/distributor/test.php on line 54
> PHP Warning:  array_merge(): Argument #2 is not an array in /home/master/NextSteep/ccxt/distributor/php/binance.php on line 852
> PHP Warning:  array_merge(): Argument #2 is not an array in /home/master/NextSteep/ccxt/distributor/php/binance.php on line 1332
> PHP Warning:  Invalid argument supplied for foreach() in /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php on line 598
> PHP Warning:  http_build_query(): Parameter 1 expected to be Array or Object.  Incorrect value given in /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php on line 603
> ccxt\ExchangeError: binance {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."}
> PHP Notice:  Undefined variable: params in /home/master/NextSteep/ccxt/distributor/test.php on line 54
> PHP Warning:  array_merge(): Argument #2 is not an array in /home/master/NextSteep/ccxt/distributor/php/binance.php on line 852
> PHP Warning:  array_merge(): Argument #2 is not an array in /home/master/NextSteep/ccxt/distributor/php/binance.php on line 1332
> PHP Warning:  Invalid argument supplied for foreach() in /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php on line 598
> PHP Warning:  http_build_query(): Parameter 1 expected to be Array or Object.  Incorrect value given in /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php on line 603
>

**Comment by kroitor** [comment]
@StasToken yep, pardon once again, basically, it's a minor typo, the `params` were redundant there. Should work now.

**Comment by StasToken** [comment]
I answer your question above I added the delay is very simple set code sleep(5)
```
   public function getOrder(int $id)
    {
sleep(5);
        $order = null;
        $this->logger->info("Get order id: " . $id);
        dump($id,$this->symbol);
        $order_open = $this->interface->fetch_order($id,$this->symbol);
        dump($order_open);
        try {
            $order_open = $this->interface->fetch_order($id,$this->symbol);
            $order = $this->orderNormalizer($order_open);
        } catch (\Exception $e) {
            $this->logger->error($e->getLine().' '.$e->getFile().' '.$e->getMessage());
            exit();
        }
        return $order;
    }
```

**Comment by kroitor** [comment]
@StasToken ok, does that snippet above work for you, though?

**Comment by StasToken** [comment]
so your code outputs the following:
https://pastebin.com/raw/7j2h6aFM 

The actions I'm trying to take for my application:
set 'rateLimit' => 500, 
add 'enableRateLimit' => true 

code

```
        include 'phar://'.__DIR__.'/ccxt.phar/ccxt.php';
        $binance     = new \ccxt\binance(array (
            'apiKey' => $api_key,
            'secret' => $secret,
            'timeout' => 50000,
            'enableRateLimit' => true
        ));
        return $binance;
```
I also tried to increase to rateLimit 1000 - but this did not solve the problem 
I get this error only for binance - for exmo it never happened which way to dig?

**Comment by StasToken** [comment]
A part of requests for an order goes away normally and the answer is correct - but at some point everything falls, and I don’t understand why.

**Comment by kroitor** [comment]
> I get this error only for binance - for exmo it never happened which way to dig?

Hard to tell without seeing the rest of your code, tbh... I my code works and fetches the order in a loop continuously without failing, then, something is not right with the rest of the code.

**Comment by StasToken** [comment]
damn I shorter refuse to believe it is some kind of magic...
I set rate limit 900 - the order was not placed - I did not do anything, I just restarted it and it was set

**Comment by StasToken** [comment]
Listen, I think the question can be closed so far because I don’t have an answer yet, but more and more work, I will try to give feedback on this subject a little later if I understand the reason

**Comment by StasToken** [comment]
```
echo "1\n";
        echo "timestamp: ".time()."\n";
        dump($this->exchange->getOrder(842943810));
        echo "2\n";echo "timestamp: ".time()."\n";
        dump($this->exchange->cancel(842943810));
        echo "Sleep 60sec\n";
        sleep(60);
        echo "3\n";echo "timestamp: ".time()."\n";
        try {
            dump($this->exchange->getOrder(842943810));
        }catch (\Exception $e){
            echo "get order error\n";
        }
        echo "4\n";
        echo "timestamp: ".time()."\n";
        dump($this->exchange->getOrder(842943810));
        die();
```

It seems to me that some kind of shit is happening in the finances... 
I have no other explanation than for the fact that they are turkeys...

> 1
> timestamp: 1574922051
> {#390
>   +"id": "842943810"
>   +"price": 7355.51
>   +"amount": 0.00272
>   +"executed": 0.0
>   +"status_exchange": "open"
>   +"type": "BUY"
> }
> 2
> timestamp: 1574922053
> {#373
>   +"id": "842943810"
>   +"price": 7355.51
>   +"amount": 0.00272
>   +"executed": 0.0
>   +"status_exchange": "canceled"
>   +"type": "BUY"
>   +"status": true
> }
> Sleep 60sec
> 3
> timestamp: 1574922116
> get order error
> Sleep 60sec
> 4
> timestamp: 1574922176
> 
> In binance.php line 1411:
>                                                       
>   [ccxt\OrderNotFound]                                
>   binance {"code":-2011,"msg":"Unknown order sent."}

**Comment by StasToken** [comment]
update: I wrote to the developers of the exchange-perhaps this error occurs on their side, at the moment they understand.

**Comment by StasToken** [comment]
In short - on the exchange said they gandon goner, and they're too busy fucking in the ass each other and they have no time to fix a bug in its sobstenno exchange

**Comment by kroitor** [comment]
@StasToken i'd recommend to start simplifying and cutting away irrelevant pieces of your code until you're left with no longer than 10-20 lines of a complete program to reproduce the issue. If my snippet above works, then by breaking down your program you will eventually locate the source of the bug. The process of debugging is iterative – simplify/cut out some irrelevant part, test if the bug is still there, and so on.

**Comment by StasToken** [comment]
@kroitor Duck, I do it! 
I can reproduce this error outside my program - can you reproduce this?
```

<?php
include 'ccxt.php';

date_default_timezone_set('UTC');

$id = 'binance'; // edit this line

// ----------------------------------------------------------------------------

// instantiate the exchange by id
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class(array(
    'apiKey' => '', // edit this line
    'secret' => '', // edit this line
    'enableRateLimit' => true,


));

var_dump($exchange->cancel_order(846633161, 'BTC/USDT'));
var_dump($exchange->fetch_order(846633161,'BTC/USDT'));
```

output

> array(17) {
>   ["info"]=>
>   array(13) {
>     ["symbol"]=>
>     string(7) "BTCUSDT"
>     ["origClientOrderId"]=>
>     string(22) "aGqrxbb9CCkAzuWUO6u2mp"
>     ["orderId"]=>
>     int(846633161)
>     ["orderListId"]=>
>     int(-1)
>     ["clientOrderId"]=>
>     string(22) "KcLH427hwylMX1ZyyvDsWK"
>     ["price"]=>
>     string(13) "7531.36000000"
>     ["origQty"]=>
>     string(10) "0.00265600"
>     ["executedQty"]=>
>     string(10) "0.00000000"
>     ["cummulativeQuoteQty"]=>
>     string(10) "0.00000000"
>     ["status"]=>
>     string(8) "CANCELED"
>     ["timeInForce"]=>
>     string(3) "GTC"
>     ["type"]=>
>     string(5) "LIMIT"
>     ["side"]=>
>     string(4) "SELL"
>   }
>   ["id"]=>
>   string(9) "846633161"
>   ["timestamp"]=>
>   NULL
>   ["datetime"]=>
>   NULL
>   ["lastTradeTimestamp"]=>
>   NULL
>   ["symbol"]=>
>   string(8) "BTC/USDT"
>   ["type"]=>
>   string(5) "limit"
>   ["side"]=>
>   string(4) "sell"
>   ["price"]=>
>   float(7531.36)
>   ["amount"]=>
>   float(0.002656)
>   ["cost"]=>
>   float(0)
>   ["average"]=>
>   NULL
>   ["filled"]=>
>   float(0)
>   ["remaining"]=>
>   float(0.002656)
>   ["status"]=>
>   string(8) "canceled"
>   ["fee"]=>
>   NULL
>   ["trades"]=>
>   NULL
> }
> PHP Fatal error:  Uncaught ccxt\OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."} in /home/master/NextSteep/ccxt/distributor/php/binance.php:1411
> Stack trace:
> #0 /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php(1392): ccxt\binance->handle_errors(400, '', 'https://api.bin...', 'GET', Array, '{"code":-2011,"...', Array, Array, NULL)
> #1 /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php(1175): ccxt\Exchange->fetch('https://api.bin...', 'GET', Array, NULL)
> #2 /home/master/NextSteep/ccxt/distributor/php/binance.php(1424): ccxt\Exchange->fetch2('order', 'private', 'GET', Array, NULL, NULL)
> #3 [internal function]: ccxt\binance->request('order', 'private', 'GET', Array)
> #4 /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php(2394): call_user_func_array(Array, Array)
> #5 /home/master/NextSteep/ccxt/distributor/php/binance.php(852): ccxt\Exchange->__call('privateGetOrder', Array)
> #6 /home/master/NextSteep/ccxt/distributor/test.php(21): ccxt\binance->fetch_order(846633161, 'BTC/USDT')
> #7 {m in /home/master/NextSteep/ccxt/distributor/php/binance.php on line 1411
> 

Evidence that this is **not due to request speed**

```

<?php
include 'ccxt.php';

date_default_timezone_set('UTC');

$id = 'binance'; // edit this line

// ----------------------------------------------------------------------------

// instantiate the exchange by id
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class(array(
    'apiKey' => '', // edit this line
    'secret' => '', // edit this line
    'enableRateLimit' => true,


));
echo "timestamp: ".time()."\n";
var_dump($exchange->cancel_order(846633169, 'BTC/USDT'));
sleep(60); // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<!!!!!!! wait 1m 
echo "timestamp: ".time()."\n";
var_dump($exchange->fetch_order(846633169,'BTC/USDT'));
```

output

> timestamp: 1575006789
> array(17) {
>   ["info"]=>
>   array(13) {
>     ["symbol"]=>
>     string(7) "BTCUSDT"
>     ["origClientOrderId"]=>
>     string(22) "AjV0S8Z3zXU44uU6sfSxBO"
>     ["orderId"]=>
>     int(846633169)
>     ["orderListId"]=>
>     int(-1)
>     ["clientOrderId"]=>
>     string(22) "GjNVOtTeBgUABp42rWgF6t"
>     ["price"]=>
>     string(13) "7382.94000000"
>     ["origQty"]=>
>     string(10) "0.00270900"
>     ["executedQty"]=>
>     string(10) "0.00000000"
>     ["cummulativeQuoteQty"]=>
>     string(10) "0.00000000"
>     ["status"]=>
>     string(8) "CANCELED"
>     ["timeInForce"]=>
>     string(3) "GTC"
>     ["type"]=>
>     string(5) "LIMIT"
>     ["side"]=>
>     string(3) "BUY"
>   }
>   ["id"]=>
>   string(9) "846633169"
>   ["timestamp"]=>
>   NULL
>   ["datetime"]=>
>   NULL
>   ["lastTradeTimestamp"]=>
>   NULL
>   ["symbol"]=>
>   string(8) "BTC/USDT"
>   ["type"]=>
>   string(5) "limit"
>   ["side"]=>
>   string(3) "buy"
>   ["price"]=>
>   float(7382.94)
>   ["amount"]=>
>   float(0.002709)
>   ["cost"]=>
>   float(0)
>   ["average"]=>
>   NULL
>   ["filled"]=>
>   float(0)
>   ["remaining"]=>
>   float(0.002709)
>   ["status"]=>
>   string(8) "canceled"
>   ["fee"]=>
>   NULL
>   ["trades"]=>
>   NULL
> }
> timestamp: 1575006852
> PHP Fatal error:  Uncaught ccxt\OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."} in /home/master/NextSteep/ccxt/distributor/php/binance.php:1411
> Stack trace:
> #0 /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php(1392): ccxt\binance->handle_errors(400, '', 'https://api.bin...', 'GET', Array, '{"code":-2011,"...', Array, Array, NULL)
> #1 /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php(1175): ccxt\Exchange->fetch('https://api.bin...', 'GET', Array, NULL)
> #2 /home/master/NextSteep/ccxt/distributor/php/binance.php(1424): ccxt\Exchange->fetch2('order', 'private', 'GET', Array, NULL, NULL)
> #3 [internal function]: ccxt\binance->request('order', 'private', 'GET', Array)
> #4 /home/master/NextSteep/ccxt/distributor/php/base/Exchange.php(2394): call_user_func_array(Array, Array)
> #5 /home/master/NextSteep/ccxt/distributor/php/binance.php(852): ccxt\Exchange->__call('privateGetOrder', Array)
> #6 /home/master/NextSteep/ccxt/distributor/test.php(23): ccxt\binance->fetch_order(846633169, 'BTC/USDT')
> #7 {m in /home/master/NextSteep/ccxt/distributor/php/binance.php on line 1411
> 

So.... test 3

```
<?php
include 'ccxt.php';

date_default_timezone_set('UTC');

$id = 'binance'; // edit this line

// ----------------------------------------------------------------------------

// instantiate the exchange by id
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class(array(
    'apiKey' => '', // edit this line
    'secret' => '', // edit this line
    'enableRateLimit' => true,


));

echo "timestamp: " . time() . "\n";
var_dump($exchange->cancel_order(846662771, 'BTC/USDT'));
sleep(60);
echo "timestamp: " . time() . "\n";

//Added exception handling to prevent the script from crashing due to a fatal error
try {
    var_dump($exchange->fetch_order(846662771, 'BTC/USDT'));
} catch (\Exception $e) {
    echo $e->getLine() . ' ' . $e->getFile() . ' ' . $e->getMessage();
}

/*
 * Creating a second instance of the class
 */
$exchange2 = new $exchange_class(array(
    'apiKey' => '', // edit this line
    'secret' => '', // edit this line
    'enableRateLimit' => true,


));

sleep(60);
echo "timestamp: " . time() . "\n";

var_dump($exchange2->fetch_order(846662771, 'BTC/USDT'));
```

```
timestamp: 1575007678
array(17) {
  ["info"]=>
  array(13) {
    ["symbol"]=>
    string(7) "BTCUSDT"
    ["origClientOrderId"]=>
    string(22) "o7pu4MylwtnmQyZSGKc8TI"
    ["orderId"]=>
    int(846662771)
    ["orderListId"]=>
    int(-1)
    ["clientOrderId"]=>
    string(22) "avtuz43yDRWYovLXevMDnZ"
    ["price"]=>
    string(13) "7536.42000000"
    ["origQty"]=>
    string(10) "0.00265400"
    ["executedQty"]=>
    string(10) "0.00000000"
    ["cummulativeQuoteQty"]=>
    string(10) "0.00000000"
    ["status"]=>
    string(8) "CANCELED"
    ["timeInForce"]=>
    string(3) "GTC"
    ["type"]=>
    string(5) "LIMIT"
    ["side"]=>
    string(4) "SELL"
  }
  ["id"]=>
  string(9) "846662771"
  ["timestamp"]=>
  NULL
  ["datetime"]=>
  NULL
  ["lastTradeTimestamp"]=>
  NULL
  ["symbol"]=>
  string(8) "BTC/USDT"
  ["type"]=>
  string(5) "limit"
  ["side"]=>
  string(4) "sell"
  ["price"]=>
  float(7536.42)
  ["amount"]=>
  float(0.002654)
  ["cost"]=>
  float(0)
  ["average"]=>
  NULL
  ["filled"]=>
  float(0)
  ["remaining"]=>
  float(0.002654)
  ["status"]=>
  string(8) "canceled"
  ["fee"]=>
  NULL
  ["trades"]=>
  NULL
}
timestamp: 1575007740
1411 /home/master/NextSteep/ccxt/distributor/php/binance.php binance {"code":-2011,"msg":"Unknown order sent."}

timestamp: 1575007800
array(17) {
  ["info"]=>
  array(18) {
    ["symbol"]=>
    string(7) "BTCUSDT"
    ["orderId"]=>
    int(846662771)
    ["orderListId"]=>
    int(-1)
    ["clientOrderId"]=>
    string(22) "o7pu4MylwtnmQyZSGKc8TI"
    ["price"]=>
    string(13) "7536.42000000"
    ["origQty"]=>
    string(10) "0.00265400"
    ["executedQty"]=>
    string(10) "0.00000000"
    ["cummulativeQuoteQty"]=>
    string(10) "0.00000000"
    ["status"]=>
    string(8) "CANCELED"
    ["timeInForce"]=>
    string(3) "GTC"
    ["type"]=>
    string(5) "LIMIT"
    ["side"]=>
    string(4) "SELL"
    ["stopPrice"]=>
    string(10) "0.00000000"
    ["icebergQty"]=>
    string(10) "0.00000000"
    ["time"]=>
    int(1575007212976)
    ["updateTime"]=>
    int(1575007680252)
    ["isWorking"]=>
    bool(true)
    ["origQuoteOrderQty"]=>
    string(10) "0.00000000"
  }
  ["id"]=>
  string(9) "846662771"
  ["timestamp"]=>
  int(1575007212976)
  ["datetime"]=>
  string(24) "2019-11-29T06:00:12.976Z"
  ["lastTradeTimestamp"]=>
  NULL
  ["symbol"]=>
  string(8) "BTC/USDT"
  ["type"]=>
  string(5) "limit"
  ["side"]=>
  string(4) "sell"
  ["price"]=>
  float(7536.42)
  ["amount"]=>
  float(0.002654)
  ["cost"]=>
  float(0)
  ["average"]=>
  NULL
  ["filled"]=>
  float(0)
  ["remaining"]=>
  float(0.002654)
  ["status"]=>
  string(8) "canceled"
  ["fee"]=>
  NULL
  ["trades"]=>
  NULL
}
```
@kroitor  - something seems to be breaking in cctx 
In the last test I create a second instance of the class to work with the exchange and through it I already receive the order correctly
It is very similar to some **bug**-try to reproduce the problem with this simple template after placing pending orders

**Comment by StasToken** [comment]
I formalize again after a successful function call **cancel_order** function call **fetch_order** Will lead to a fatal error 
```

$class_instance_cctx1->cancel_order('1234','BTC/USDT')
$class_instance_cctx1->fetch_order('1234','BTC/USDT') // fatal error - the exchange cannot find an order
```
But! - if you call the same function in another instance of the class without any delay
```
$class_instance_cctx1->cancel_order('1234','BTC/USDT')
$class_instance_cctx2->fetch_order('1234','BTC/USDT') // things are good!
```

**Comment by kroitor** [comment]
@StasToken This has something to do with the timing of order canceling in Binance's engine.

I suggest to rule out CCXT completely to make sure this is not a bug in CCXT. Take another "official" php implementation and try it yourself:

1. Visit https://github.com/binance-exchange/php-binance-api
2. install it
3. Edit and run this code (there may be typos, haven't tested it myself)

```PHP
<?php

require 'vendor/autoload.php';

$api = new Binance\API("<api key>","<secret>");

$orderid = 846662771;
$symbol = 'BTCUSDT';

echo "timestamp: " . time() . "\n";

// Cancel an Order
$response = $api->cancel($symbol, $orderid);
print_r($response);

sleep(60);
echo "timestamp: " . time() . "\n";

// Get Order Status
$orderstatus = $api->orderStatus($symbol, $orderid);
print_r($orderstatus);

sleep(60);
echo "timestamp: " . time() . "\n";

// Get Order Status
$orderstatus = $api->orderStatus($symbol, $orderid);
print_r($orderstatus);
```

↑ It does the same thing your code above does, but without CCXT. Comparing the results could shed some light on the cause of the issue.

Most often these issues are related to the timing within the exchange's engine. It takes time to move the order from the table of active orders to the table of inactive orders, and if you query it in between – that can yield error -2011.

More about it:

- https://github.com/askmike/gekko/issues/2762
- https://www.reddit.com/r/binance/comments/7hzoz6/unknown_order_sent_cancelled_limit_orders_still/

Let me know if you can reproduce the same issue without CCXT, like shown above.

**Comment by StasToken** [comment]
@kroitor - with all due respect to you - please read my previous post there  **I denied the fact that the exchange does not have time to move the order to the canceled ones after waiting 60 seconds** and got an error when using cctx - however, if you create a second class cctx and use it to obtain data about the order **without delay** then this works
What about your request to check the code:
_output_

> timestamp: 1575035437
> Array
> (
>     [symbol] => BTCUSDT
>     [origClientOrderId] => 12xCQK7b0DjYzZ7sHdV5nm
>     [orderId] => 847946179
>     [orderListId] => -1
>     [clientOrderId] => U7VLYGjXtdqtI2gwedbsJI
>     [price] => 10000.00000000
>     [origQty] => 0.00299900
>     [executedQty] => 0.00000000
>     [cummulativeQuoteQty] => 0.00000000
>     [status] => CANCELED
>     [timeInForce] => GTC
>     [type] => LIMIT
>     [side] => SELL
> )
> timestamp: 1575035498
> Array
> (
>     [symbol] => BTCUSDT
>     [orderId] => 847946179
>     [orderListId] => -1
>     [clientOrderId] => 12xCQK7b0DjYzZ7sHdV5nm
>     [price] => 10000.00000000
>     [origQty] => 0.00299900
>     [executedQty] => 0.00000000
>     [cummulativeQuoteQty] => 0.00000000
>     [status] => CANCELED
>     [timeInForce] => GTC
>     [type] => LIMIT
>     [side] => SELL
>     [stopPrice] => 0.00000000
>     [icebergQty] => 0.00000000
>     [time] => 1575033018368
>     [updateTime] => 1575035438384
>     [isWorking] => 1
>     [origQuoteOrderQty] => 0.00000000
> )
> timestamp: 1575035559
> Array
> (
>     [symbol] => BTCUSDT
>     [orderId] => 847946179
>     [orderListId] => -1
>     [clientOrderId] => 12xCQK7b0DjYzZ7sHdV5nm
>     [price] => 10000.00000000
>     [origQty] => 0.00299900
>     [executedQty] => 0.00000000
>     [cummulativeQuoteQty] => 0.00000000
>     [status] => CANCELED
>     [timeInForce] => GTC
>     [type] => LIMIT
>     [side] => SELL
>     [stopPrice] => 0.00000000
>     [icebergQty] => 0.00000000
>     [time] => 1575033018368
>     [updateTime] => 1575035438384
>     [isWorking] => 1
>     [origQuoteOrderQty] => 0.00000000
> )
> 
also I do it without delay **grind on timestamp**

_output_

> timestamp: 1575035702
> Array
> (
>     [symbol] => BTCUSDT
>     [origClientOrderId] => web_08d494a50d9a45ca9f4774ed749ec6f0
>     [orderId] => 848089173
>     [orderListId] => -1
>     [clientOrderId] => eYNPeZkXWU9pWEld9WvpjU
>     [price] => 5000.00000000
>     [origQty] => 0.00299900
>     [executedQty] => 0.00000000
>     [cummulativeQuoteQty] => 0.00000000
>     [status] => CANCELED
>     [timeInForce] => GTC
>     [type] => LIMIT
>     [side] => BUY
> )
> timestamp: 1575035703
> Array
> (
>     [symbol] => BTCUSDT
>     [orderId] => 848089173
>     [orderListId] => -1
>     [clientOrderId] => web_08d494a50d9a45ca9f4774ed749ec6f0
>     [price] => 5000.00000000
>     [origQty] => 0.00299900
>     [executedQty] => 0.00000000
>     [cummulativeQuoteQty] => 0.00000000
>     [status] => CANCELED
>     [timeInForce] => GTC
>     [type] => LIMIT
>     [side] => BUY
>     [stopPrice] => 0.00000000
>     [icebergQty] => 0.00000000
>     [time] => 1575035129793
>     [updateTime] => 1575035703299
>     [isWorking] => 1
>     [origQuoteOrderQty] => 0.00000000
> )
> timestamp: 1575035704
> Array
> (
>     [symbol] => BTCUSDT
>     [orderId] => 848089173
>     [orderListId] => -1
>     [clientOrderId] => web_08d494a50d9a45ca9f4774ed749ec6f0
>     [price] => 5000.00000000
>     [origQty] => 0.00299900
>     [executedQty] => 0.00000000
>     [cummulativeQuoteQty] => 0.00000000
>     [status] => CANCELED
>     [timeInForce] => GTC
>     [type] => LIMIT
>     [side] => BUY
>     [stopPrice] => 0.00000000
>     [icebergQty] => 0.00000000
>     [time] => 1575035129793
>     [updateTime] => 1575035703299
>     [isWorking] => 1
>     [origQuoteOrderQty] => 0.00000000
> )
> 


**Such an error appears only in cctx** 
The sequence of steps to get this bug in cctx 
1) cancel order 
2) get it - error
------------------------------
1) cancel order
2) sleep 60 
3) get it - error

**THIS IS NOT TIME** - something breaks in cctx and the request goes wrong

**Comment by StasToken** [comment]
> Most often these issues are related to the timing within the exchange's engine. It takes time to move the order from the table of active orders to the table of inactive orders, and if you query it in between – that can yield error -2011.

**I wait a whole minute when using cctx the exchange cannot move the order so much!**
In the above utilities by **you** - I make requests in the second test without any delays and they work out correctly

**Comment by kroitor** [comment]
@StasToken going to debug it this weekend, will figure it out. Need some time to reproduce it on my side and resolve this. Will get back to you with my findings.

**Comment by kroitor** [comment]
@StasToken i've reproduced the issue on my side, it was indeed a bug in CCXT that was introduced here: https://github.com/ccxt/ccxt/issues/5914

The source of the problem was related to cookie handling with Cloudfront (cf).

We have added the `curl_close` call to each `fetch` call. And it should work in CCXT version 1.20.17. Thank you for the feedback! Let us know if you have any further difficulties with it.

**Comment by kroitor** [comment]
@StasToken 

P.S. The new build 1.20.17 will arrive in 15 minutes.

**Comment by StasToken** [comment]
@kroitor Hi thanks for the quick fix! - He created a lot of problems for me ... now everything works as it should - thanks!
