### ISSUE TITLE
Binance: "Timestamp for this request is 1000ms ahead of the server's time %s

### ISSUE THREAD

**Issue by nucwzq** [ccxt/ccxt#773]
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/account?timestamp=1512607422293&signature=1f47f5f............................ 400 Bad Request  {"code":-1021,"msg":"Timestamp for this request is 1000ms ahead of the server's time %s."}

**Comment by kroitor** [comment]
You need to synchronize your clock with a time server to keep up with them, or you can add a `recvWindow` extra param, like so:

```Python
binance.fetch_balance({'recvWindow': 10000000})
```

↑ let me know if the above solves your problem.

**Comment by nucwzq** [comment]
How to synchronize the clock with a time server to keep up with them? You mean I have to synchronize the clock every time when the program is run.

**Comment by kroitor** [comment]
@nucwzq no, it depends on your system, but on Windows and Mac you can just turn time synchronization in your time / system settings, and on linux you can run a daemon that pings the time server in background and adjusts your system clock if needed. That is not a part of your program, the task of timesynch is usually solved with existing software and OSes.

**Comment by kroitor** [comment]
However, Binance offers a `recvWindow` param if you have a time synch issue, and it should actually solve that problem for you.

**Comment by nucwzq** [comment]
@kroitor OK, Sorry, I still have little idea. So, what should I do in my program, and I run it in win10 sys.

**Comment by kroitor** [comment]
> So, what should I do in my program

```
binance.fetch_balance({'recvWindow': 10000000})
```

**Comment by nucwzq** [comment]
@kroitor 
I changed the program "all_balance = bina.fetch_balance()," into "all_balance = bina.fetch_balance({'recvWindow': 10000000}),". It still have the error: ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/account?timestamp=1512609171808&recvWindow=10000000&signature=69f6... Bad Request  {"code":-1021,"msg":"Timestamp for this request is 1000ms ahead of the server's time %s."}

**Comment by kroitor** [comment]
@nucwzq 

https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#timing-security

A very dirty **not recommended hack** that will make it work:

```Python
bina.nonce = lambda: bina.milliseconds() - 1000
all_balance = bina.fetch_balance()
```

However, I **highly recommend** to set up time synchronization in your Windows 10 settings:

![bwdwt](https://user-images.githubusercontent.com/1294454/33693875-43f29442-db06-11e7-86e3-429356c9de46.png)

**Comment by nucwzq** [comment]
@kroitor thank u! I try the second methods you mentioned above, and it seems work now.

**Comment by kroitor** [comment]
@nucwzq thanks for letting us know! Cheers!

**Comment by MelbourneDeveloper** [comment]
There is certainly some kind of bug around this... I've tried everything.

Here's my code in C#. You will need to make some guesses about what it is doing:

            var currentDateTimeUTC = await APIHelpers.GetUtcDateTime();
            var queryString = $"api/v3/account?recvWindow=10000000&timestamp={currentDateTimeUTC.Ticks}";
            var uri = new Uri($"{RESTClient.BaseUri}{queryString}");
            var encryptor = new HMACSHA256(Encoding.UTF8.GetBytes(ApiSecret));
            queryString += $"&signature={ByteToString(encryptor.ComputeHash(Encoding.UTF8.GetBytes(uri.Query.Replace("?", ""))))}";
            RESTClient.Headers.Add("X-MBX-APIKEY", ApiKey);
            var retVal = await RESTClient.GetAsync<string>(queryString);

I've tried getting the time from my local clock, and I've tried getting the time from http://www.convert-unix-time.com. But, it just keeps telling me Timestamp for this request is 1000ms ahead of the server's time. I've tried subtracting seconds off the time and it makes no difference. 

Besides all this, we an never assume that a user's clock is in sync.

**Comment by MelbourneDeveloper** [comment]
Even when I get the time from the Binance server (and check that it is correct), I still get the error:

            var binanceTime = await RESTClient.GetAsync<BinanceTime>("/api/v1/time");
            var currentDateTimeUTC = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddMilliseconds(binanceTime.serverTime);
            System.Diagnostics.Debug.WriteLine("binance" + currentDateTimeUTC);
            var queryString = $"api/v3/account?recvWindow=10000000&timestamp={currentDateTimeUTC.Ticks}";
            var uri = new Uri($"{RESTClient.BaseUri}{queryString}");
            var encryptor = new HMACSHA256(Encoding.UTF8.GetBytes(ApiSecret));
            queryString += $"&signature={ByteToString(encryptor.ComputeHash(Encoding.UTF8.GetBytes(uri.Query.Replace("?", ""))))}";
            RESTClient.Headers.Add("X-MBX-APIKEY", ApiKey);
            var retVal = await RESTClient.GetAsync<string>(queryString);

**Comment by dmitriz** [comment]
I also had this issue and here is what I found that might be helpful to others coming here:

- The reason was the wrong timezone. I was traveling but did not change the timezone. After the change it worked.

- The other proposed solution to add `{'recvWindow': 10000000}` did not solve the problem for me. According to the Binance API logic described in  https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#timing-security,
```js
if (timestamp < (serverTime + 1000) && (serverTime - timestamp) <= recvWindow) {
  // process request
} else {
  // reject request
}
```
Thus the problem persists if the first check fails.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/936#issuecomment-353774479
- https://github.com/ccxt/ccxt/issues/850#issuecomment-353774447

**Comment by digitalchaotics** [comment]
I cured the problem here by setting the Win10 Internet Time Settings as noted by @kroitor , making sure to use "time.nist.gov", and NOT "time.windows.com"

**Comment by bizl** [comment]
I#m using "time.windows.com" and using getting timestamp as shown in the amended code below and it works. However I've got internet time syncing every 5 minutes. I'll disable and holler if it bugs out in future. 

 ```
var timestamp= new DateTimeOffset(DateTime.UtcNow).ToUnixTimeMilliseconds().ToString();
        var queryString = $"api/v3/account?recvWindow=5000&timestamp={timestamp.Ticks}";
        var uri = new Uri($"{RESTClient.BaseUri}{queryString}");
        var encryptor = new HMACSHA256(Encoding.UTF8.GetBytes(ApiSecret));
        queryString += $"&signature={ByteToString(encryptor.ComputeHash(Encoding.UTF8.GetBytes(uri.Query.Replace("?", ""))))}";
        RESTClient.Headers.Add("X-MBX-APIKEY", ApiKey);
        var retVal = await RESTClient.GetAsync<string>(queryString);
```

**Comment by WesamMikhail** [comment]
@kroitor The question I have is: why doesn't this bug happen in the browser when using binance's website? if the system clock is out of sync, then the website shouldn't work either as the same would apply there... 

The following code piece is in their site's source, but it doesn't say much as even using this piece of code via a script still generates the "1000 ahead of time" error.

`var start=new Date().getTime();
$http.get('/exchange/public/serverTime').success(function(data){
   var end=new Date().getTime();
   var diff=new Date().getTime()-data+(end-start)/2;
   $rootScope.today = new Date(new Date().getTime()-diff);
   $interval(function(){
	   $rootScope.today = new Date(new Date().getTime()-diff);
   },1000)
})`

**Comment by kroitor** [comment]
@WesamMikhail 

> The question I have is: why doesn't this bug happen in the browser when using binance's website?

Well, you've answered your question yourself ) A decent question usually contains the answer itself ))

First, their website uses a different API, afaik, Binance isn't a single engineer, they have separate teams working on different parts of their system, and the trading API is separated from the Web API or withdraw API – all of those are run by different teams. And the web internals arent' publicly documented, of course. So, the first half of the answer is: because web API is different from trading API.

Yet, this does not feel like a satisfying answer to me, so, yes, they also do the half-RTT adjustment, as shown in your snippet. And btw, we also have that feature available in ccxt, you just need to:

```JavaScript
const adjustForTimeDifference = true
const options = { adjustForTimeDifference }
const exchange = new ccxt.binance ({ options }) // and that's it )
```

or just...

```JavaScript
const exchange = new ccxt.binance ({ 'options': { 'adjustForTimeDifference': true }}) // and that's it )
```

That option will enable the adjustment in the same fashion as in your snippet. Let us know if it does not help.

**Comment by WesamMikhail** [comment]
Thanks for the reply.

I noticed that they are using a different private api for the web version. But yea, I thought it would return the same value as the public api and should be treated identically, hence my confusion. Turns out after closer examination that this might not be the case at all.

Anyway, the half cycle adjustment works sometimes actually but in a lot of cases (ex. when I am on mobile connection) it doesn't. So for those who are looking for a solution to the problem: what I ended up doing was half-RTT followed by reducing the current local timestamp by 10000 and added a huge recvWindow. Doing that seems to have solved the vast majority of issues for me as the discrepancy between server and client seemed to always be in the 5000ms range

**Comment by kroitor** [comment]
@WesamMikhail you might really want to also read through https://github.com/ccxt/ccxt/issues/850 as these issues are of the same nature actually, and that second post also has some clues and possible solutions. Hope it helps.

**Comment by rhubear25** [comment]
> 
> A very dirty **not recommended hack** that will make it work:
> 
> ```python
> bina.nonce = lambda: bina.milliseconds() - 1000  # this line is only needed once in the beginning of your program
> all_balance = bina.fetch_balance()

lamba: Client.milliseconds() - 1000  <===  IS WORKING FOR ME

I have been having intermittant problems with Binance Nonce (1000 ms ahead of server time).

Previously Binance commands WERE WORKING.  I just synced time manually, using ccxt async library.

Each new day when I tried connecting to Binance, I had nonce errors.

I ended up changing my PC time to UTC (no summer time adjust).
I added to Win7 Task Scheduler:   start /B C:\Windows\System32\w32tm.exe /resync
(everything after 'start' in param field)... 
(/B runs background task, otherwise you have a window popping up for a second then disappearing)
Scheduled for EVERY 5 MINS.

STILL HAD NONCE ISSUES ON A NEW DAY.

Today when I was trying Binance again, NONCE ERROR AGAIN.... So I tried adding in the Trick above.

THANKYOU FOR THE SOLUTION !!!

**Comment by Unterarzt** [comment]
Cheers, just syncing the clock worked without having to do a workaround.

**Comment by OliverSolomon** [comment]
You need to sync your clock.

On Linux, you can just go to the terminal and restart the time server using:
``` 
sudo systemctl restart ntp 
```

you can find out more on restarting the time server [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-debian-10)

**Comment by qq776355102** [comment]
> 使用“time.nist.gov”，而不是“time.windows.com”

这对我有用
